// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const categoryAncestors = `-- name: CategoryAncestors :many
WITH RECURSIVE chain (id, parent_id, depth) AS (
    SELECT c.id, c.parent_id, 1
    FROM categories c
    WHERE c.id = $1
    UNION ALL
    SELECT p.id, p.parent_id, chain.depth + 1
    FROM categories p
    JOIN chain ON p.id = chain.parent_id
    WHERE chain.depth < 100
)
SELECT chain.id::uuid
FROM chain
ORDER BY depth
`

// CategoryAncestors returns the category and its ancestors, nearest first.
// The depth bound stops the walk if a concurrent move ever created a cycle.
func (q *Queries) CategoryAncestors(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, categoryAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var chain_id uuid.UUID
		if err := rows.Scan(&chain_id); err != nil {
			return nil, err
		}
		items = append(items, chain_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (id, tenant_id, name, parent_id, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCategoryParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	ParentID  *uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.Exec(ctx, createCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.ParentID,
		arg.CreatedAt,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, tenant_id, name, parent_id, created_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, tenant_id, name, parent_id, created_at
FROM categories
ORDER BY name, id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :execrows
UPDATE categories
SET name = $2, parent_id = $3
WHERE id = $1
`

type UpdateCategoryParams struct {
	ID       uuid.UUID
	Name     string
	ParentID *uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCategory, arg.ID, arg.Name, arg.ParentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
