// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*)
FROM products
WHERE ($1::boolean IS NULL OR active = $1)
  AND ($2::uuid IS NULL OR category_id = $2)
`

type CountProductsParams struct {
	Active     *bool
	CategoryID *uuid.UUID
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.Active, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchProducts = `-- name: CountSearchProducts :one
SELECT count(*)
FROM products
WHERE ($1::boolean IS NULL OR active = $1)
  AND ($2::uuid IS NULL OR category_id = $2)
  AND (sku = $3
       OR barcode = $4
       OR search_name LIKE ALL (SELECT '%' || f_unaccent(lower(term)) || '%' FROM unnest($5::text[]) AS term))
`

type CountSearchProductsParams struct {
	Active     *bool
	CategoryID *uuid.UUID
	Sku        string
	Barcode    *string
	Terms      []string
}

func (q *Queries) CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchProducts,
		arg.Active,
		arg.CategoryID,
		arg.Sku,
		arg.Barcode,
		arg.Terms,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (id, tenant_id, sku, barcode, name, description, category_id, base_unit, cost, price, tax_rate, active, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateProductParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Sku         string
	Barcode     *string
	Name        string
	Description string
	CategoryID  *uuid.UUID
	BaseUnit    string
	Cost        decimal.Decimal
	Price       decimal.Decimal
	TaxRate     decimal.Decimal
	Active      bool
	CreatedAt   time.Time
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct,
		arg.ID,
		arg.TenantID,
		arg.Sku,
		arg.Barcode,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.BaseUnit,
		arg.Cost,
		arg.Price,
		arg.TaxRate,
		arg.Active,
		arg.CreatedAt,
	)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, tenant_id, sku, barcode, name, description, category_id, base_unit, cost, price, tax_rate, active, created_at
FROM products
WHERE id = $1
`

type GetProductRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Sku         string
	Barcode     *string
	Name        string
	Description string
	CategoryID  *uuid.UUID
	BaseUnit    string
	Cost        decimal.Decimal
	Price       decimal.Decimal
	TaxRate     decimal.Decimal
	Active      bool
	CreatedAt   time.Time
}

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Description,
		&i.CategoryID,
		&i.BaseUnit,
		&i.Cost,
		&i.Price,
		&i.TaxRate,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, tenant_id, sku, barcode, name, description, category_id, base_unit, cost, price, tax_rate, active, created_at
FROM products
WHERE ($1::boolean IS NULL OR active = $1)
  AND ($2::uuid IS NULL OR category_id = $2)
ORDER BY name, id
LIMIT $4 OFFSET $3
`

type ListProductsParams struct {
	Active     *bool
	CategoryID *uuid.UUID
	RowOffset  int32
	RowLimit   int32
}

type ListProductsRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Sku         string
	Barcode     *string
	Name        string
	Description string
	CategoryID  *uuid.UUID
	BaseUnit    string
	Cost        decimal.Decimal
	Price       decimal.Decimal
	TaxRate     decimal.Decimal
	Active      bool
	CreatedAt   time.Time
}

// ListProducts pages the products without a search text, by name.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Active,
		arg.CategoryID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Sku,
			&i.Barcode,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.BaseUnit,
			&i.Cost,
			&i.Price,
			&i.TaxRate,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, tenant_id, sku, barcode, name, description, category_id, base_unit, cost, price, tax_rate, active, created_at
FROM products
WHERE ($1::boolean IS NULL OR active = $1)
  AND ($2::uuid IS NULL OR category_id = $2)
  AND (sku = $3
       OR barcode = $4
       OR search_name LIKE ALL (SELECT '%' || f_unaccent(lower(term)) || '%' FROM unnest($5::text[]) AS term))
ORDER BY coalesce(sku = $3 OR barcode = $4, false) DESC,
         similarity(search_name, f_unaccent(lower($6))) DESC,
         name, id
LIMIT $8 OFFSET $7
`

type SearchProductsParams struct {
	Active     *bool
	CategoryID *uuid.UUID
	Sku        string
	Barcode    *string
	Terms      []string
	Text       string
	RowOffset  int32
	RowLimit   int32
}

type SearchProductsRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Sku         string
	Barcode     *string
	Name        string
	Description string
	CategoryID  *uuid.UUID
	BaseUnit    string
	Cost        decimal.Decimal
	Price       decimal.Decimal
	TaxRate     decimal.Decimal
	Active      bool
	CreatedAt   time.Time
}

// SearchProducts matches an exact SKU or barcode, or names containing every
// term (case- and accent-insensitive). Terms arrive with LIKE wildcards
// escaped. Exact codes come first, then the names most similar (pg_trgm) to
// the whole text.
func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts,
		arg.Active,
		arg.CategoryID,
		arg.Sku,
		arg.Barcode,
		arg.Terms,
		arg.Text,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsRow
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Sku,
			&i.Barcode,
			&i.Name,
			&i.Description,
			&i.CategoryID,
			&i.BaseUnit,
			&i.Cost,
			&i.Price,
			&i.TaxRate,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :execrows
UPDATE products
SET sku = $2, barcode = $3, name = $4, description = $5, category_id = $6,
    base_unit = $7, cost = $8, price = $9, tax_rate = $10, active = $11
WHERE id = $1
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Sku         string
	Barcode     *string
	Name        string
	Description string
	CategoryID  *uuid.UUID
	BaseUnit    string
	Cost        decimal.Decimal
	Price       decimal.Decimal
	TaxRate     decimal.Decimal
	Active      bool
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.Sku,
		arg.Barcode,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.BaseUnit,
		arg.Cost,
		arg.Price,
		arg.TaxRate,
		arg.Active,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
