/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description El proceso está vivo. No revisa dependencias.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Las dependencias (base de datos) responden y la instancia puede recibir tráfico.
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar una empresa
         * @description Crea la empresa (tenant) y su usuario dueño, e inicia la sesión.
         */
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Si el correo y la contraseña coinciden en varias empresas, responde 409 con la lista de
         *     empresas; el cliente repite la request con el `tenant_id` elegido.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renovar la sesión
         * @description Cambia el refresh token de la cookie por uno nuevo y emite un access token nuevo.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar sesión
         * @description Revoca el refresh token de la cookie (y su familia) y borra la cookie. Es idempotente.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usuario actual
         * @description El usuario autenticado, su empresa y sus permisos.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar productos
         * @description Lista los productos de la empresa. Con `q` busca por nombre (cada palabra debe aparecer, sin
         *     importar tildes ni mayúsculas) o por SKU o código de barras exactos, que salen primero.
         *     Sin `q`, ordena por nombre.
         */
        get: operations["listProducts"];
        put?: never;
        /** Crear un producto */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        /**
         * Ver un producto
         * @description Devuelve el producto aunque esté inactivo.
         */
        get: operations["getProduct"];
        /**
         * Editar un producto
         * @description Reemplaza todos los datos editables. El precio de un producto inactivo no se puede cambiar.
         */
        put: operations["updateProduct"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desactivar un producto
         * @description El producto deja de venderse, pero se conserva para el historial. Es idempotente.
         */
        post: operations["deactivateProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activar un producto
         * @description El producto se puede vender de nuevo. Es idempotente.
         */
        post: operations["activateProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar categorías
         * @description Todas las categorías de la empresa, ordenadas por nombre. El árbol se arma con `parent_id`.
         */
        get: operations["listCategories"];
        put?: never;
        /** Crear una categoría */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Editar una categoría
         * @description Cambia el nombre y el padre. Sin `parent_id`, la categoría queda en la raíz.
         */
        put: operations["updateCategory"];
        post?: never;
        /**
         * Borrar una categoría
         * @description Solo se puede borrar una categoría sin productos ni subcategorías.
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar sedes
         * @description Todas las sedes y bodegas de la empresa, activas o no, ordenadas por nombre.
         */
        get: operations["listLocations"];
        put?: never;
        /** Crear una sede */
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{locationId}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                locationId: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        /**
         * Existencias de una sede
         * @description Los productos que han tenido movimientos en la sede, con su cantidad y costo promedio. Un producto sin
         *     movimientos no aparece (su existencia es cero).
         */
        get: operations["listStock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/kardex": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        /**
         * Kardex de un producto
         * @description Los movimientos del producto, del más reciente al más antiguo. `balance_after` es el saldo en la sede
         *     del movimiento justo después de él.
         */
        get: operations["getKardex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar una entrada de mercancía
         * @description Suma la cantidad a la existencia de la sede y recalcula el costo promedio ponderado. Sirve también para el
         *     inventario inicial.
         */
        post: operations["receiveStock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un ajuste de inventario
         * @description Corrige la existencia en la cantidad indicada (positiva suma, negativa resta) por un motivo obligatorio. Se
         *     valora al costo promedio y no lo cambia.
         */
        post: operations["adjustStock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trasladar mercancía entre sedes
         * @description Saca la cantidad de la sede de origen y la entra en la de destino, valorada al costo promedio del origen.
         *     Los dos movimientos comparten la misma referencia de traslado.
         */
        post: operations["transferStock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "error": {
         *         "code": "insufficient_stock",
         *         "message": "No hay stock suficiente de Cemento gris 50kg"
         *       }
         *     }
         */
        Error: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            /** @description Código estable, en snake_case, para que el cliente decida qué hacer. */
            code: string;
            /** @description Mensaje en español que se puede mostrar al usuario. */
            message: string;
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok";
        };
        ReadyStatus: {
            /** @enum {string} */
            status: "ready";
        };
        SignUpRequest: {
            /**
             * @description Nombre de la empresa.
             * @example Ferretería El Tornillo
             */
            tenant_name: string;
            /**
             * @description NIT con dígito de verificación (`890903938-8`).
             * @example 890903938-8
             */
            nit: string;
            /**
             * @description Nombre del dueño.
             * @example Ana Gómez
             */
            name: string;
            /** @example ana@eltornillo.co */
            email: string;
            /**
             * Format: password
             * @description Entre 8 y 72 caracteres.
             */
            password: string;
        };
        LoginRequest: {
            email: string;
            /** Format: password */
            password: string;
            /**
             * Format: uuid
             * @description Empresa elegida tras una respuesta 409 `tenant_selection_required`.
             */
            tenant_id?: string;
        };
        AuthSession: {
            /** @description JWT para el header `Authorization: Bearer`. */
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /**
             * @description Segundos de vida del access token.
             * @example 900
             */
            expires_in: number;
            user: components["schemas"]["Me"];
        };
        Me: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            tenant_name: string;
            name: string;
            email: string;
            /** @enum {string} */
            role: "owner" | "admin" | "cashier" | "warehouse";
            /**
             * @description Permisos del rol, para mostrar u ocultar acciones en la UI.
             * @example [
             *       "catalog:read",
             *       "sales:create"
             *     ]
             */
            permissions: string[];
        };
        TenantSelectionRequired: {
            error: components["schemas"]["ErrorDetail"];
            tenants: components["schemas"]["TenantOption"][];
        };
        TenantOption: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /**
         * @description Monto en pesos colombianos, como decimal en string (hasta 4 decimales).
         * @example 12500.00
         */
        Money: string;
        /**
         * @description Tasa de IVA como fracción decimal (`0.19` es 19 %), menor que 1 y con hasta 4 decimales.
         * @example 0.19
         */
        TaxRate: string;
        /**
         * @description Unidad base en la que se cuenta y se vende el producto.
         * @enum {string}
         */
        UnitOfMeasure: "und" | "m" | "kg" | "l" | "caja" | "rollo" | "bulto" | "galon";
        ProductInput: {
            /**
             * @description Código interno, único en la empresa. Se guarda en mayúsculas.
             * @example TUB-PVC-12
             */
            sku: string;
            /**
             * @description Código de barras, único en la empresa. Vacío u omitido si no tiene.
             * @example 7701234567890
             */
            barcode?: string;
            /** @example Tubo PVC presión 1/2 pulgada */
            name: string;
            description?: string;
            /** Format: uuid */
            category_id?: string | null;
            base_unit: components["schemas"]["UnitOfMeasure"];
            cost: components["schemas"]["Money"];
            price: components["schemas"]["Money"];
            tax_rate: components["schemas"]["TaxRate"];
        };
        /**
         * @description Un producto del catálogo. El precio no incluye IVA; `price_with_tax` lo incluye, redondeado a 2 decimales.
         *     `cost` y `margin_percent` solo se envían a quien puede editar el catálogo (`catalog:write`).
         */
        Product: {
            /** Format: uuid */
            id: string;
            /** @example TUB-PVC-12 */
            sku: string;
            /** @description Se omite si el producto no tiene. */
            barcode?: string;
            name: string;
            /** @description Se omite si está vacía. */
            description?: string;
            /**
             * Format: uuid
             * @description Se omite si el producto no tiene categoría.
             */
            category_id?: string;
            base_unit: components["schemas"]["UnitOfMeasure"];
            cost?: components["schemas"]["Money"];
            price: components["schemas"]["Money"];
            price_with_tax: components["schemas"]["Money"];
            tax_rate: components["schemas"]["TaxRate"];
            /**
             * @description Margen sobre el precio de venta, en porcentaje. Es negativo si el precio está por debajo del costo.
             * @example 16.6667
             */
            margin_percent?: string;
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        ProductPage: {
            items: components["schemas"]["Product"][];
            /** @description Cantidad total de productos que cumplen el filtro, sin paginar. */
            total: number;
        };
        CategoryInput: {
            /** @example Plomería */
            name: string;
            /**
             * Format: uuid
             * @description Categoría padre. Omitido o `null`, la categoría queda en la raíz.
             */
            parent_id?: string | null;
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * Format: uuid
             * @description Se omite si la categoría está en la raíz.
             */
            parent_id?: string;
            /** Format: date-time */
            created_at: string;
        };
        CategoryList: {
            items: components["schemas"]["Category"][];
        };
        /**
         * @description Cantidad en la unidad base del producto, como decimal en string (hasta 4 decimales).
         * @example 2.5
         */
        Quantity: string;
        /**
         * @description Cantidad con signo (negativa si sale), como decimal en string (hasta 4 decimales).
         * @example -3
         */
        SignedQuantity: string;
        LocationInput: {
            /** @example Bodega principal */
            name: string;
        };
        Location: {
            /** Format: uuid */
            id: string;
            name: string;
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        LocationList: {
            items: components["schemas"]["Location"][];
        };
        /**
         * @description La existencia de un producto en una sede. `quantity` es negativa solo si la empresa permite vender sin
         *     stock. `average_cost` (costo promedio ponderado, sin IVA) solo se envía a quien tiene `catalog:write`.
         */
        StockLevel: {
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            location_id: string;
            quantity: components["schemas"]["SignedQuantity"];
            average_cost?: components["schemas"]["Money"];
        };
        StockLevelPage: {
            items: components["schemas"]["StockLevel"][];
            /** @description Cantidad total de existencias que cumplen el filtro, sin paginar. */
            total: number;
        };
        DocumentRef: {
            /** @enum {string} */
            kind: "purchase" | "sale" | "transfer";
            /** Format: uuid */
            id: string;
        };
        /**
         * @description Un movimiento del kardex. `quantity` es positiva si entra y negativa si sale. `unit_cost` y
         *     `average_cost_after` solo se envían a quien tiene `catalog:write`. `reference` se omite si no hay documento.
         */
        StockMovement: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            location_id: string;
            /** @enum {string} */
            type: "purchase_in" | "sale_out" | "adjustment" | "transfer_out" | "transfer_in";
            quantity: components["schemas"]["SignedQuantity"];
            unit_cost?: components["schemas"]["Money"];
            balance_after: components["schemas"]["SignedQuantity"];
            average_cost_after?: components["schemas"]["Money"];
            /** @description Motivo del ajuste. Se omite en los demás tipos. */
            reason?: string;
            reference?: components["schemas"]["DocumentRef"];
            /**
             * Format: uuid
             * @description Quién registró el movimiento.
             */
            user_id: string;
            /** Format: date-time */
            occurred_at: string;
        };
        StockMovementPage: {
            items: components["schemas"]["StockMovement"][];
            /** @description Cantidad total de movimientos que cumplen el filtro, sin paginar. */
            total: number;
        };
        ReceiptInput: {
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            location_id: string;
            quantity: components["schemas"]["Quantity"];
            unit_cost: components["schemas"]["Money"];
        };
        AdjustmentInput: {
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            location_id: string;
            quantity: components["schemas"]["SignedQuantity"];
            /** @example Bulto roto en la bodega */
            reason: string;
        };
        TransferInput: {
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            from_location_id: string;
            /** Format: uuid */
            to_location_id: string;
            quantity: components["schemas"]["Quantity"];
        };
        TransferResult: {
            out: components["schemas"]["StockMovement"];
            in: components["schemas"]["StockMovement"];
        };
    };
    responses: {
        /** @description La request no cumple el contrato (`code` = `invalid_request`). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Falta el token o no es válido (`code` = `unauthorized`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description El usuario no tiene permiso para esta acción (`code` = `forbidden`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description El recurso no existe (`code` = `not_found` u otro más específico). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description La operación choca con el estado actual (por ejemplo, un SKU duplicado). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description La request es válida, pero viola una regla de negocio (por ejemplo, `insufficient_stock`). */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error inesperado del servidor (`code` = `internal_error`). */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Cantidad máxima de resultados. */
        Limit: number;
        /** @description Cantidad de resultados a saltar. */
        Offset: number;
        ProductId: string;
        CategoryId: string;
        LocationId: string;
        /** @description Refresh token. Lo pone la API; el navegador lo envía solo a `/api/v1/auth`. */
        RefreshCookie: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Cookie `cuadra_refresh` con el refresh token (HttpOnly, Secure, SameSite=Strict, ruta `/api/v1/auth`).
         *     Al cerrar sesión o si la sesión no es válida, la cookie se borra.
         */
        SetRefreshCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El proceso responde. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La instancia está lista. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyStatus"];
                };
            };
            /** @description Alguna dependencia no responde (`code` = `not_ready`). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description Empresa creada; la sesión queda iniciada. */
            201: {
                headers: {
                    "Set-Cookie": components["headers"]["SetRefreshCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            /**
             * @description Algún dato no cumple las reglas (`invalid_email`, `invalid_nit`, `invalid_nit_check_digit`,
             *     `password_too_short`, `password_too_long`, `invalid_tenant_name`, `invalid_user_name`).
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Sesión iniciada. */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SetRefreshCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Correo o contraseña incorrectos (`code` = `invalid_credentials`). No revela si el correo existe. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La empresa está suspendida (`code` = `tenant_suspended`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Las credenciales son válidas en varias empresas (`code` = `tenant_selection_required`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSelectionRequired"];
                };
            };
            /** @description Demasiados intentos (`code` = `too_many_requests`). */
            429: {
                headers: {
                    /** @description Segundos que hay que esperar antes de intentar de nuevo. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description Refresh token. Lo pone la API; el navegador lo envía solo a `/api/v1/auth`. */
                cuadra_refresh?: components["parameters"]["RefreshCookie"];
            };
        };
        requestBody?: never;
        responses: {
            /** @description Sesión renovada. */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SetRefreshCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            /** @description Falta la cookie, o el refresh token no es válido, venció o fue reutilizado (`code` = `invalid_session`). */
            401: {
                headers: {
                    "Set-Cookie": components["headers"]["SetRefreshCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description Refresh token. Lo pone la API; el navegador lo envía solo a `/api/v1/auth`. */
                cuadra_refresh?: components["parameters"]["RefreshCookie"];
            };
        };
        requestBody?: never;
        responses: {
            /** @description Sesión cerrada. */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["SetRefreshCookie"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El usuario autenticado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                /**
                 * @description Texto a buscar.
                 * @example tubo pvc
                 */
                q?: string;
                /** @description Solo los productos de esta categoría. */
                category_id?: string;
                /** @description Productos activos (por defecto), inactivos o todos. */
                status?: "active" | "inactive" | "all";
                /** @description Cantidad máxima de resultados. */
                limit?: components["parameters"]["Limit"];
                /** @description Cantidad de resultados a saltar. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Una página de productos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Producto creado (activo). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description El SKU o el código de barras ya existen en la empresa (`sku_taken`, `barcode_taken`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Algún dato no cumple las reglas (`invalid_sku`, `invalid_barcode`, `invalid_product_name`,
             *     `invalid_description`, `invalid_price`, `invalid_cost`, `invalid_tax_rate`, `category_not_found`).
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El producto. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description El producto actualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description El SKU o el código de barras ya existen en la empresa (`sku_taken`, `barcode_taken`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description Algún dato no cumple las reglas (los mismos códigos de crear un producto) o se cambió el precio
             *     de un producto inactivo (`product_inactive`).
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    deactivateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El producto, inactivo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    activateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El producto, activo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Las categorías. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description Categoría creada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description El nombre no es válido (`invalid_category_name`) o el padre no existe (`category_not_found`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryInput"];
            };
        };
        responses: {
            /** @description La categoría actualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description El nombre no es válido (`invalid_category_name`), el padre no existe (`category_not_found`), el padre
             *     es la misma categoría (`invalid_category_parent`) o el movimiento formaría un ciclo (`category_cycle`).
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoryId: components["parameters"]["CategoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categoría borrada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description La categoría tiene productos o subcategorías (`category_in_use`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listLocations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Las sedes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationInput"];
            };
        };
        responses: {
            /** @description Sede creada (activa). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Ya existe una sede con ese nombre (`location_name_taken`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description El nombre no es válido (`invalid_location_name`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listStock: {
        parameters: {
            query?: {
                /** @description Solo la existencia de este producto. */
                product_id?: string;
                /** @description Cantidad máxima de resultados. */
                limit?: components["parameters"]["Limit"];
                /** @description Cantidad de resultados a saltar. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                locationId: components["parameters"]["LocationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Una página de existencias. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockLevelPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getKardex: {
        parameters: {
            query?: {
                /** @description Solo los movimientos de esta sede. */
                location_id?: string;
                /** @description Cantidad máxima de resultados. */
                limit?: components["parameters"]["Limit"];
                /** @description Cantidad de resultados a saltar. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Una página del kardex. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovementPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    receiveStock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptInput"];
            };
        };
        responses: {
            /** @description El movimiento registrado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovement"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /**
             * @description Algún dato no cumple las reglas (`invalid_quantity`, `invalid_unit_cost`, `product_not_found`,
             *     `location_not_found`, `location_inactive`).
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    adjustStock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustmentInput"];
            };
        };
        responses: {
            /** @description El movimiento registrado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovement"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /**
             * @description Algún dato no cumple las reglas (`invalid_quantity`, `adjustment_reason_required`,
             *     `adjustment_reason_too_long`, `insufficient_stock`, `product_not_found`, `location_not_found`,
             *     `location_inactive`).
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    transferStock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferInput"];
            };
        };
        responses: {
            /** @description Los dos movimientos del traslado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /**
             * @description Algún dato no cumple las reglas (`invalid_quantity`, `same_location_transfer`, `insufficient_stock`,
             *     `product_not_found`, `location_not_found`, `location_inactive`).
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
