//go:build go1.22

// Package inventoryapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package inventoryapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DocumentRefKind.
const (
	Purchase DocumentRefKind = "purchase"
	Sale     DocumentRefKind = "sale"
	Transfer DocumentRefKind = "transfer"
)

// Valid indicates whether the value is a known member of the DocumentRefKind enum.
func (e DocumentRefKind) Valid() bool {
	switch e {
	case Purchase:
		return true
	case Sale:
		return true
	case Transfer:
		return true
	default:
		return false
	}
}

// Defines values for StockMovementType.
const (
	Adjustment  StockMovementType = "adjustment"
	PurchaseIn  StockMovementType = "purchase_in"
	SaleOut     StockMovementType = "sale_out"
	TransferIn  StockMovementType = "transfer_in"
	TransferOut StockMovementType = "transfer_out"
)

// Valid indicates whether the value is a known member of the StockMovementType enum.
func (e StockMovementType) Valid() bool {
	switch e {
	case Adjustment:
		return true
	case PurchaseIn:
		return true
	case SaleOut:
		return true
	case TransferIn:
		return true
	case TransferOut:
		return true
	default:
		return false
	}
}

// AdjustmentInput defines model for AdjustmentInput.
type AdjustmentInput struct {
	LocationId openapi_types.UUID `json:"location_id"`
	ProductId  openapi_types.UUID `json:"product_id"`

	// Quantity Cantidad con signo (negativa si sale), como decimal en string (hasta 4 decimales).
	//
	// Example: -3
	Quantity SignedQuantity `json:"quantity"`

	// Reason Example: Bulto roto en la bodega
	Reason string `json:"reason"`
}

// DocumentRef defines model for DocumentRef.
type DocumentRef struct {
	Id   openapi_types.UUID `json:"id"`
	Kind DocumentRefKind    `json:"kind"`
}

// DocumentRefKind defines model for DocumentRef.Kind.
type DocumentRefKind string

// Error Example: {"error":{"code":"insufficient_stock","message":"No hay stock suficiente de Cemento gris 50kg"}}
type Error struct {
	Error ErrorDetail `json:"error"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Code Código estable, en snake_case, para que el cliente decida qué hacer.
	Code string `json:"code"`

	// Message Mensaje en español que se puede mostrar al usuario.
	Message string `json:"message"`
}

// Location defines model for Location.
type Location struct {
	Active    bool               `json:"active"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// LocationInput defines model for LocationInput.
type LocationInput struct {
	// Name Example: Bodega principal
	Name string `json:"name"`
}

// LocationList defines model for LocationList.
type LocationList struct {
	Items []Location `json:"items"`
}

// Money Monto en pesos colombianos, como decimal en string (hasta 4 decimales).
//
// Example: 12500.00
type Money = string

// Quantity Cantidad en la unidad base del producto, como decimal en string (hasta 4 decimales).
//
// Example: 2.5
type Quantity = string

// ReceiptInput defines model for ReceiptInput.
type ReceiptInput struct {
	LocationId openapi_types.UUID `json:"location_id"`
	ProductId  openapi_types.UUID `json:"product_id"`

	// Quantity Cantidad en la unidad base del producto, como decimal en string (hasta 4 decimales).
	//
	// Example: 2.5
	Quantity Quantity `json:"quantity"`

	// UnitCost Monto en pesos colombianos, como decimal en string (hasta 4 decimales).
	//
	// Example: 12500.00
	UnitCost Money `json:"unit_cost"`
}

// SignedQuantity Cantidad con signo (negativa si sale), como decimal en string (hasta 4 decimales).
//
// Example: -3
type SignedQuantity = string

// StockLevel La existencia de un producto en una sede. `quantity` es negativa solo si la empresa permite vender sin
// stock. `average_cost` (costo promedio ponderado, sin IVA) solo se envía a quien tiene `catalog:write`.
type StockLevel struct {
	// AverageCost Monto en pesos colombianos, como decimal en string (hasta 4 decimales).
	//
	// Example: 12500.00
	AverageCost *Money             `json:"average_cost,omitempty"`
	LocationId  openapi_types.UUID `json:"location_id"`
	ProductId   openapi_types.UUID `json:"product_id"`

	// Quantity Cantidad con signo (negativa si sale), como decimal en string (hasta 4 decimales).
	//
	// Example: -3
	Quantity SignedQuantity `json:"quantity"`
}

// StockLevelPage defines model for StockLevelPage.
type StockLevelPage struct {
	Items []StockLevel `json:"items"`

	// Total Cantidad total de existencias que cumplen el filtro, sin paginar.
	Total int `json:"total"`
}

// StockMovement Un movimiento del kardex. `quantity` es positiva si entra y negativa si sale. `unit_cost` y
// `average_cost_after` solo se envían a quien tiene `catalog:write`. `reference` se omite si no hay documento.
type StockMovement struct {
	// AverageCostAfter Monto en pesos colombianos, como decimal en string (hasta 4 decimales).
	//
	// Example: 12500.00
	AverageCostAfter *Money `json:"average_cost_after,omitempty"`

	// BalanceAfter Cantidad con signo (negativa si sale), como decimal en string (hasta 4 decimales).
	//
	// Example: -3
	BalanceAfter SignedQuantity     `json:"balance_after"`
	Id           openapi_types.UUID `json:"id"`
	LocationId   openapi_types.UUID `json:"location_id"`
	OccurredAt   time.Time          `json:"occurred_at"`
	ProductId    openapi_types.UUID `json:"product_id"`

	// Quantity Cantidad con signo (negativa si sale), como decimal en string (hasta 4 decimales).
	//
	// Example: -3
	Quantity SignedQuantity `json:"quantity"`

	// Reason Motivo del ajuste. Se omite en los demás tipos.
	Reason    *string           `json:"reason,omitempty"`
	Reference *DocumentRef      `json:"reference,omitempty"`
	Type      StockMovementType `json:"type"`

	// UnitCost Monto en pesos colombianos, como decimal en string (hasta 4 decimales).
	//
	// Example: 12500.00
	UnitCost *Money `json:"unit_cost,omitempty"`

	// UserId Quién registró el movimiento.
	UserId openapi_types.UUID `json:"user_id"`
}

// StockMovementType defines model for StockMovement.Type.
type StockMovementType string

// StockMovementPage defines model for StockMovementPage.
type StockMovementPage struct {
	Items []StockMovement `json:"items"`

	// Total Cantidad total de movimientos que cumplen el filtro, sin paginar.
	Total int `json:"total"`
}

// TransferInput defines model for TransferInput.
type TransferInput struct {
	FromLocationId openapi_types.UUID `json:"from_location_id"`
	ProductId      openapi_types.UUID `json:"product_id"`

	// Quantity Cantidad en la unidad base del producto, como decimal en string (hasta 4 decimales).
	//
	// Example: 2.5
	Quantity     Quantity           `json:"quantity"`
	ToLocationId openapi_types.UUID `json:"to_location_id"`
}

// TransferResult defines model for TransferResult.
type TransferResult struct {
	// In Un movimiento del kardex. `quantity` es positiva si entra y negativa si sale. `unit_cost` y
	// `average_cost_after` solo se envían a quien tiene `catalog:write`. `reference` se omite si no hay documento.
	In StockMovement `json:"in"`

	// Out Un movimiento del kardex. `quantity` es positiva si entra y negativa si sale. `unit_cost` y
	// `average_cost_after` solo se envían a quien tiene `catalog:write`. `reference` se omite si no hay documento.
	Out StockMovement `json:"out"`
}

// CategoryId defines model for CategoryId.
type CategoryId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// LocationId defines model for LocationId.
type LocationId = openapi_types.UUID

// Offset defines model for Offset.
type Offset = int

// ProductId defines model for ProductId.
type ProductId = openapi_types.UUID

// BadRequest Example: {"error":{"code":"insufficient_stock","message":"No hay stock suficiente de Cemento gris 50kg"}}
type BadRequest = Error

// Forbidden Example: {"error":{"code":"insufficient_stock","message":"No hay stock suficiente de Cemento gris 50kg"}}
type Forbidden = Error

// InternalError Example: {"error":{"code":"insufficient_stock","message":"No hay stock suficiente de Cemento gris 50kg"}}
type InternalError = Error

// NotFound Example: {"error":{"code":"insufficient_stock","message":"No hay stock suficiente de Cemento gris 50kg"}}
type NotFound = Error

// Unauthorized Example: {"error":{"code":"insufficient_stock","message":"No hay stock suficiente de Cemento gris 50kg"}}
type Unauthorized = Error

// ListStockParams defines parameters for ListStock.
type ListStockParams struct {
	// ProductId Solo la existencia de este producto.
	ProductId *openapi_types.UUID `form:"product_id,omitempty" json:"product_id,omitempty"`

	// Limit Cantidad máxima de resultados.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Cantidad de resultados a saltar.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetKardexParams defines parameters for GetKardex.
type GetKardexParams struct {
	// LocationId Solo los movimientos de esta sede.
	LocationId *openapi_types.UUID `form:"location_id,omitempty" json:"location_id,omitempty"`

	// Limit Cantidad máxima de resultados.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Cantidad de resultados a saltar.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdjustStockJSONRequestBody defines body for AdjustStock for application/json ContentType.
type AdjustStockJSONRequestBody = AdjustmentInput

// ReceiveStockJSONRequestBody defines body for ReceiveStock for application/json ContentType.
type ReceiveStockJSONRequestBody = ReceiptInput

// TransferStockJSONRequestBody defines body for TransferStock for application/json ContentType.
type TransferStockJSONRequestBody = TransferInput

// CreateLocationJSONRequestBody defines body for CreateLocation for application/json ContentType.
type CreateLocationJSONRequestBody = LocationInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// AdjustStock Registrar un ajuste de inventario
	// (POST /api/v1/inventory/adjustments)
	AdjustStock(w http.ResponseWriter, r *http.Request)
	// ReceiveStock Registrar una entrada de mercancía
	// (POST /api/v1/inventory/receipts)
	ReceiveStock(w http.ResponseWriter, r *http.Request)
	// TransferStock Trasladar mercancía entre sedes
	// (POST /api/v1/inventory/transfers)
	TransferStock(w http.ResponseWriter, r *http.Request)
	// ListLocations Listar sedes
	// (GET /api/v1/locations)
	ListLocations(w http.ResponseWriter, r *http.Request)
	// CreateLocation Crear una sede
	// (POST /api/v1/locations)
	CreateLocation(w http.ResponseWriter, r *http.Request)
	// ListStock Existencias de una sede
	// (GET /api/v1/locations/{locationId}/stock)
	ListStock(w http.ResponseWriter, r *http.Request, locationId LocationId, params ListStockParams)
	// GetKardex Kardex de un producto
	// (GET /api/v1/products/{productId}/kardex)
	GetKardex(w http.ResponseWriter, r *http.Request, productId ProductId, params GetKardexParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AdjustStock operation middleware
func (siw *ServerInterfaceWrapper) AdjustStock(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdjustStock(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveStock operation middleware
func (siw *ServerInterfaceWrapper) ReceiveStock(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveStock(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TransferStock operation middleware
func (siw *ServerInterfaceWrapper) TransferStock(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TransferStock(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLocations operation middleware
func (siw *ServerInterfaceWrapper) ListLocations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLocations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLocation operation middleware
func (siw *ServerInterfaceWrapper) CreateLocation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLocation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStock operation middleware
func (siw *ServerInterfaceWrapper) ListStock(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "locationId" -------------
	var locationId LocationId

	err = runtime.BindStyledParameterWithOptions("simple", "locationId", r.PathValue("locationId"), &locationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "locationId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListStockParams

	// ------------- Optional query parameter "product_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "product_id", r.URL.Query(), &params.ProductId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "product_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "product_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStock(w, r, locationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetKardex operation middleware
func (siw *ServerInterfaceWrapper) GetKardex(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", r.PathValue("productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetKardexParams

	// ------------- Optional query parameter "location_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "location_id", r.URL.Query(), &params.LocationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "location_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "location_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetKardex(w, r, productId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/locations", wrapper.ListLocations)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/locations", wrapper.CreateLocation)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/locations/{locationId}/stock", wrapper.ListStock)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/products/{productId}/kardex", wrapper.GetKardex)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/inventory/receipts", wrapper.ReceiveStock)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/inventory/adjustments", wrapper.AdjustStock)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/inventory/transfers", wrapper.TransferStock)

	return m
}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type AdjustStockRequestObject struct {
	Body *AdjustStockJSONRequestBody
}

type AdjustStockResponseObject interface {
	VisitAdjustStockResponse(w http.ResponseWriter) error
}

type AdjustStock201JSONResponse StockMovement

func (response AdjustStock201JSONResponse) VisitAdjustStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AdjustStock400JSONResponse struct{ BadRequestJSONResponse }

func (response AdjustStock400JSONResponse) VisitAdjustStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AdjustStock401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AdjustStock401JSONResponse) VisitAdjustStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AdjustStock403JSONResponse struct{ ForbiddenJSONResponse }

func (response AdjustStock403JSONResponse) VisitAdjustStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AdjustStock422JSONResponse Error

func (response AdjustStock422JSONResponse) VisitAdjustStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type AdjustStock500JSONResponse struct{ InternalErrorJSONResponse }

func (response AdjustStock500JSONResponse) VisitAdjustStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveStockRequestObject struct {
	Body *ReceiveStockJSONRequestBody
}

type ReceiveStockResponseObject interface {
	VisitReceiveStockResponse(w http.ResponseWriter) error
}

type ReceiveStock201JSONResponse StockMovement

func (response ReceiveStock201JSONResponse) VisitReceiveStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveStock400JSONResponse struct{ BadRequestJSONResponse }

func (response ReceiveStock400JSONResponse) VisitReceiveStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveStock401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ReceiveStock401JSONResponse) VisitReceiveStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveStock403JSONResponse struct{ ForbiddenJSONResponse }

func (response ReceiveStock403JSONResponse) VisitReceiveStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveStock422JSONResponse Error

func (response ReceiveStock422JSONResponse) VisitReceiveStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ReceiveStock500JSONResponse struct{ InternalErrorJSONResponse }

func (response ReceiveStock500JSONResponse) VisitReceiveStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type TransferStockRequestObject struct {
	Body *TransferStockJSONRequestBody
}

type TransferStockResponseObject interface {
	VisitTransferStockResponse(w http.ResponseWriter) error
}

type TransferStock201JSONResponse TransferResult

func (response TransferStock201JSONResponse) VisitTransferStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type TransferStock400JSONResponse struct{ BadRequestJSONResponse }

func (response TransferStock400JSONResponse) VisitTransferStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type TransferStock401JSONResponse struct{ UnauthorizedJSONResponse }

func (response TransferStock401JSONResponse) VisitTransferStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type TransferStock403JSONResponse struct{ ForbiddenJSONResponse }

func (response TransferStock403JSONResponse) VisitTransferStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type TransferStock422JSONResponse Error

func (response TransferStock422JSONResponse) VisitTransferStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type TransferStock500JSONResponse struct{ InternalErrorJSONResponse }

func (response TransferStock500JSONResponse) VisitTransferStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListLocationsRequestObject struct {
}

type ListLocationsResponseObject interface {
	VisitListLocationsResponse(w http.ResponseWriter) error
}

type ListLocations200JSONResponse LocationList

func (response ListLocations200JSONResponse) VisitListLocationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLocations401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListLocations401JSONResponse) VisitListLocationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListLocations403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListLocations403JSONResponse) VisitListLocationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListLocations500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListLocations500JSONResponse) VisitListLocationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLocationRequestObject struct {
	Body *CreateLocationJSONRequestBody
}

type CreateLocationResponseObject interface {
	VisitCreateLocationResponse(w http.ResponseWriter) error
}

type CreateLocation201JSONResponse Location

func (response CreateLocation201JSONResponse) VisitCreateLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLocation400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateLocation400JSONResponse) VisitCreateLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLocation401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateLocation401JSONResponse) VisitCreateLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLocation403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateLocation403JSONResponse) VisitCreateLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLocation409JSONResponse Error

func (response CreateLocation409JSONResponse) VisitCreateLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLocation422JSONResponse Error

func (response CreateLocation422JSONResponse) VisitCreateLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateLocation500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateLocation500JSONResponse) VisitCreateLocationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListStockRequestObject struct {
	LocationId LocationId `json:"locationId"`
	Params     ListStockParams
}

type ListStockResponseObject interface {
	VisitListStockResponse(w http.ResponseWriter) error
}

type ListStock200JSONResponse StockLevelPage

func (response ListStock200JSONResponse) VisitListStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListStock400JSONResponse struct{ BadRequestJSONResponse }

func (response ListStock400JSONResponse) VisitListStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListStock401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListStock401JSONResponse) VisitListStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListStock403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListStock403JSONResponse) VisitListStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListStock404JSONResponse struct{ NotFoundJSONResponse }

func (response ListStock404JSONResponse) VisitListStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListStock500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListStock500JSONResponse) VisitListStockResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetKardexRequestObject struct {
	ProductId ProductId `json:"productId"`
	Params    GetKardexParams
}

type GetKardexResponseObject interface {
	VisitGetKardexResponse(w http.ResponseWriter) error
}

type GetKardex200JSONResponse StockMovementPage

func (response GetKardex200JSONResponse) VisitGetKardexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetKardex400JSONResponse struct{ BadRequestJSONResponse }

func (response GetKardex400JSONResponse) VisitGetKardexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetKardex401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetKardex401JSONResponse) VisitGetKardexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetKardex403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetKardex403JSONResponse) VisitGetKardexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetKardex500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetKardex500JSONResponse) VisitGetKardexResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// AdjustStock Registrar un ajuste de inventario
	// (POST /api/v1/inventory/adjustments)
	AdjustStock(ctx context.Context, request AdjustStockRequestObject) (AdjustStockResponseObject, error)
	// ReceiveStock Registrar una entrada de mercancía
	// (POST /api/v1/inventory/receipts)
	ReceiveStock(ctx context.Context, request ReceiveStockRequestObject) (ReceiveStockResponseObject, error)
	// TransferStock Trasladar mercancía entre sedes
	// (POST /api/v1/inventory/transfers)
	TransferStock(ctx context.Context, request TransferStockRequestObject) (TransferStockResponseObject, error)
	// ListLocations Listar sedes
	// (GET /api/v1/locations)
	ListLocations(ctx context.Context, request ListLocationsRequestObject) (ListLocationsResponseObject, error)
	// CreateLocation Crear una sede
	// (POST /api/v1/locations)
	CreateLocation(ctx context.Context, request CreateLocationRequestObject) (CreateLocationResponseObject, error)
	// ListStock Existencias de una sede
	// (GET /api/v1/locations/{locationId}/stock)
	ListStock(ctx context.Context, request ListStockRequestObject) (ListStockResponseObject, error)
	// GetKardex Kardex de un producto
	// (GET /api/v1/products/{productId}/kardex)
	GetKardex(ctx context.Context, request GetKardexRequestObject) (GetKardexResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AdjustStock operation middleware
func (sh *strictHandler) AdjustStock(w http.ResponseWriter, r *http.Request) {
	var request AdjustStockRequestObject

	var body AdjustStockJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AdjustStock(ctx, request.(AdjustStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdjustStock")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AdjustStockResponseObject); ok {
		if err := validResponse.VisitAdjustStockResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReceiveStock operation middleware
func (sh *strictHandler) ReceiveStock(w http.ResponseWriter, r *http.Request) {
	var request ReceiveStockRequestObject

	var body ReceiveStockJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReceiveStock(ctx, request.(ReceiveStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReceiveStock")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReceiveStockResponseObject); ok {
		if err := validResponse.VisitReceiveStockResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TransferStock operation middleware
func (sh *strictHandler) TransferStock(w http.ResponseWriter, r *http.Request) {
	var request TransferStockRequestObject

	var body TransferStockJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TransferStock(ctx, request.(TransferStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TransferStock")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TransferStockResponseObject); ok {
		if err := validResponse.VisitTransferStockResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListLocations operation middleware
func (sh *strictHandler) ListLocations(w http.ResponseWriter, r *http.Request) {
	var request ListLocationsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListLocations(ctx, request.(ListLocationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLocations")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListLocationsResponseObject); ok {
		if err := validResponse.VisitListLocationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateLocation operation middleware
func (sh *strictHandler) CreateLocation(w http.ResponseWriter, r *http.Request) {
	var request CreateLocationRequestObject

	var body CreateLocationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateLocation(ctx, request.(CreateLocationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateLocation")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateLocationResponseObject); ok {
		if err := validResponse.VisitCreateLocationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListStock operation middleware
func (sh *strictHandler) ListStock(w http.ResponseWriter, r *http.Request, locationId LocationId, params ListStockParams) {
	var request ListStockRequestObject

	request.LocationId = locationId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListStock(ctx, request.(ListStockRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListStock")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListStockResponseObject); ok {
		if err := validResponse.VisitListStockResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetKardex operation middleware
func (sh *strictHandler) GetKardex(w http.ResponseWriter, r *http.Request, productId ProductId, params GetKardexParams) {
	var request GetKardexRequestObject

	request.ProductId = productId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetKardex(ctx, request.(GetKardexRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetKardex")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetKardexResponseObject); ok {
		if err := validResponse.VisitGetKardexResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
