// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :exec
INSERT INTO locations (id, tenant_id, name, active, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateLocationParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Active    bool
	CreatedAt time.Time
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) error {
	_, err := q.db.Exec(ctx, createLocation,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Active,
		arg.CreatedAt,
	)
	return err
}

const getLocation = `-- name: GetLocation :one
SELECT id, tenant_id, name, active, created_at
FROM locations
WHERE id = $1
`

func (q *Queries) GetLocation(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, tenant_id, name, active, created_at
FROM locations
ORDER BY name, id
`

func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
