// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getStockPolicy = `-- name: GetStockPolicy :one
SELECT allow_negative_stock
FROM inventory_settings
WHERE tenant_id = $1
`

func (q *Queries) GetStockPolicy(ctx context.Context, tenantID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getStockPolicy, tenantID)
	var allow_negative_stock bool
	err := row.Scan(&allow_negative_stock)
	return allow_negative_stock, err
}
