// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countKardex = `-- name: CountKardex :one
SELECT count(*)
FROM stock_movements
WHERE product_id = $1
  AND ($2::uuid IS NULL OR location_id = $2)
`

type CountKardexParams struct {
	ProductID  uuid.UUID
	LocationID *uuid.UUID
}

func (q *Queries) CountKardex(ctx context.Context, arg CountKardexParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKardex, arg.ProductID, arg.LocationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStockLevels = `-- name: CountStockLevels :one
SELECT count(*)
FROM stock_levels
WHERE location_id = $1
  AND ($2::uuid IS NULL OR product_id = $2)
`

type CountStockLevelsParams struct {
	LocationID uuid.UUID
	ProductID  *uuid.UUID
}

func (q *Queries) CountStockLevels(ctx context.Context, arg CountStockLevelsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStockLevels, arg.LocationID, arg.ProductID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureStockLevel = `-- name: EnsureStockLevel :exec
INSERT INTO stock_levels (tenant_id, product_id, location_id, quantity, average_cost, updated_at)
VALUES ($1, $2, $3, 0, 0, $4)
ON CONFLICT (tenant_id, product_id, location_id) DO NOTHING
`

type EnsureStockLevelParams struct {
	TenantID   uuid.UUID
	ProductID  uuid.UUID
	LocationID uuid.UUID
	UpdatedAt  time.Time
}

// EnsureStockLevel creates an empty level if there is none, so the next
// statement can lock it. It fails on the foreign keys if the product or the
// location does not exist in the tenant.
func (q *Queries) EnsureStockLevel(ctx context.Context, arg EnsureStockLevelParams) error {
	_, err := q.db.Exec(ctx, ensureStockLevel,
		arg.TenantID,
		arg.ProductID,
		arg.LocationID,
		arg.UpdatedAt,
	)
	return err
}

const insertStockMovement = `-- name: InsertStockMovement :exec
INSERT INTO stock_movements (id, tenant_id, product_id, location_id, type, quantity, unit_cost, balance_after,
                             average_cost_after, reason, reference_kind, reference_id, user_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertStockMovementParams struct {
	ID               uuid.UUID
	TenantID         uuid.UUID
	ProductID        uuid.UUID
	LocationID       uuid.UUID
	Type             string
	Quantity         decimal.Decimal
	UnitCost         decimal.Decimal
	BalanceAfter     decimal.Decimal
	AverageCostAfter decimal.Decimal
	Reason           string
	ReferenceKind    *string
	ReferenceID      *uuid.UUID
	UserID           uuid.UUID
	OccurredAt       time.Time
}

func (q *Queries) InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) error {
	_, err := q.db.Exec(ctx, insertStockMovement,
		arg.ID,
		arg.TenantID,
		arg.ProductID,
		arg.LocationID,
		arg.Type,
		arg.Quantity,
		arg.UnitCost,
		arg.BalanceAfter,
		arg.AverageCostAfter,
		arg.Reason,
		arg.ReferenceKind,
		arg.ReferenceID,
		arg.UserID,
		arg.OccurredAt,
	)
	return err
}

const listKardex = `-- name: ListKardex :many
SELECT id, tenant_id, product_id, location_id, type, quantity, unit_cost, balance_after,
       average_cost_after, reason, reference_kind, reference_id, user_id, occurred_at
FROM stock_movements
WHERE product_id = $1
  AND ($2::uuid IS NULL OR location_id = $2)
ORDER BY occurred_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListKardexParams struct {
	ProductID  uuid.UUID
	LocationID *uuid.UUID
	RowOffset  int32
	RowLimit   int32
}

// ListKardex pages a product's movements, newest first.
func (q *Queries) ListKardex(ctx context.Context, arg ListKardexParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listKardex,
		arg.ProductID,
		arg.LocationID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.LocationID,
			&i.Type,
			&i.Quantity,
			&i.UnitCost,
			&i.BalanceAfter,
			&i.AverageCostAfter,
			&i.Reason,
			&i.ReferenceKind,
			&i.ReferenceID,
			&i.UserID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockLevels = `-- name: ListStockLevels :many
SELECT tenant_id, product_id, location_id, quantity, average_cost
FROM stock_levels
WHERE location_id = $1
  AND ($2::uuid IS NULL OR product_id = $2)
ORDER BY product_id
LIMIT $4 OFFSET $3
`

type ListStockLevelsParams struct {
	LocationID uuid.UUID
	ProductID  *uuid.UUID
	RowOffset  int32
	RowLimit   int32
}

type ListStockLevelsRow struct {
	TenantID    uuid.UUID
	ProductID   uuid.UUID
	LocationID  uuid.UUID
	Quantity    decimal.Decimal
	AverageCost decimal.Decimal
}

func (q *Queries) ListStockLevels(ctx context.Context, arg ListStockLevelsParams) ([]ListStockLevelsRow, error) {
	rows, err := q.db.Query(ctx, listStockLevels,
		arg.LocationID,
		arg.ProductID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockLevelsRow
	for rows.Next() {
		var i ListStockLevelsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ProductID,
			&i.LocationID,
			&i.Quantity,
			&i.AverageCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStockLevels = `-- name: LockStockLevels :many
SELECT tenant_id, product_id, location_id, quantity, average_cost
FROM stock_levels
WHERE product_id = $1 AND location_id = ANY($2::uuid[])
ORDER BY location_id
FOR UPDATE
`

type LockStockLevelsParams struct {
	ProductID   uuid.UUID
	LocationIds []uuid.UUID
}

type LockStockLevelsRow struct {
	TenantID    uuid.UUID
	ProductID   uuid.UUID
	LocationID  uuid.UUID
	Quantity    decimal.Decimal
	AverageCost decimal.Decimal
}

// LockStockLevels locks the levels of a product at the given locations, in
// location order, until the transaction ends.
func (q *Queries) LockStockLevels(ctx context.Context, arg LockStockLevelsParams) ([]LockStockLevelsRow, error) {
	rows, err := q.db.Query(ctx, lockStockLevels, arg.ProductID, arg.LocationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockStockLevelsRow
	for rows.Next() {
		var i LockStockLevelsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ProductID,
			&i.LocationID,
			&i.Quantity,
			&i.AverageCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStockLevel = `-- name: UpdateStockLevel :execrows
UPDATE stock_levels
SET quantity = $3, average_cost = $4, updated_at = $5
WHERE product_id = $1 AND location_id = $2
`

type UpdateStockLevelParams struct {
	ProductID   uuid.UUID
	LocationID  uuid.UUID
	Quantity    decimal.Decimal
	AverageCost decimal.Decimal
	UpdatedAt   time.Time
}

func (q *Queries) UpdateStockLevel(ctx context.Context, arg UpdateStockLevelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStockLevel,
		arg.ProductID,
		arg.LocationID,
		arg.Quantity,
		arg.AverageCost,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
