// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, tenant_id, user_id, family_id, token_hash, expires_at, created_at, revoked_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	CreatedAt time.Time
	RevokedAt *time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.RevokedAt,
	)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, tenant_id, user_id, family_id, token_hash, expires_at, created_at, revoked_at
FROM refresh_tokens
WHERE tenant_id = $1 AND token_hash = $2
`

type GetRefreshTokenByHashParams struct {
	TenantID  uuid.UUID
	TokenHash []byte
}

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, arg GetRefreshTokenByHashParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, arg.TenantID, arg.TokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens
SET revoked_at = $3
WHERE tenant_id = $1 AND id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	TenantID  uuid.UUID
	ID        uuid.UUID
	RevokedAt *time.Time
}

// RevokeRefreshToken revokes a token only if it is still live: 0 rows means
// another transaction revoked it first.
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshToken, arg.TenantID, arg.ID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :execrows
UPDATE refresh_tokens
SET revoked_at = $3
WHERE tenant_id = $1 AND family_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenFamilyParams struct {
	TenantID  uuid.UUID
	FamilyID  uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenFamily, arg.TenantID, arg.FamilyID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
