// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name, nit, status, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateTenantParams struct {
	ID        uuid.UUID
	Name      string
	Nit       string
	Status    string
	CreatedAt time.Time
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Nit,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, nit, status, created_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Nit,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :execrows
UPDATE tenants
SET name = $2, status = $3
WHERE id = $1
`

type UpdateTenantParams struct {
	ID     uuid.UUID
	Name   string
	Status string
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTenant, arg.ID, arg.Name, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
