// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, tenant_id, email, name, password_hash, role, active, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateUserParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	Role         string
	Active       bool
	CreatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
		arg.Active,
		arg.CreatedAt,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, email, name, password_hash, role, active, created_at
FROM users
WHERE tenant_id = $1 AND id = $2
`

type GetUserParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.TenantID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, name, password_hash, role, active, created_at
FROM users
WHERE tenant_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	TenantID uuid.UUID
	Email    string
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users
SET name = $3, password_hash = $4, role = $5, active = $6
WHERE tenant_id = $1 AND id = $2
`

type UpdateUserParams struct {
	TenantID     uuid.UUID
	ID           uuid.UUID
	Name         string
	PasswordHash string
	Role         string
	Active       bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUser,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.PasswordHash,
		arg.Role,
		arg.Active,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
