// Package apispec exposes the embedded OpenAPI contract (api/openapi.yaml):
// the request validator and the development docs read it at runtime.
// spec.gen.go is generated by `make openapi`.
package apispec

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3filter"
	"github.com/getkin/kin-openapi/routers"
	nethttpmiddleware "github.com/oapi-codegen/nethttp-middleware"

	"github.com/brayangomez22/cuadra-app/backend/internal/platform/httpx"
)

// Load returns the embedded spec after checking that it is a valid OpenAPI
// document. Each call returns a fresh copy the caller may modify.
func Load(ctx context.Context) (*openapi3.T, error) {
	spec, err := GetSpec()
	if err != nil {
		return nil, fmt.Errorf("load openapi spec: %w", err)
	}
	if err := spec.Validate(ctx); err != nil {
		return nil, fmt.Errorf("invalid openapi spec: %w", err)
	}
	return spec, nil
}

// NewValidator returns a middleware that rejects requests that do not match
// spec (unknown route, method, parameter or body) with the standard Error
// schema, before they reach the generated handlers. It modifies spec.
//
// It checks the request's shape, not who sends it: the security
// requirements are enforced by the auth middleware (RequireAuth), which owns
// the token rules. The servers block is ignored, so the Host header is not
// matched against it.
func NewValidator(spec *openapi3.T, log *slog.Logger) (func(http.Handler) http.Handler, error) {
	// The middleware panics on a spec it cannot route; report it as an error.
	spec.Servers = nil
	if err := spec.Validate(context.Background()); err != nil {
		return nil, fmt.Errorf("invalid openapi spec: %w", err)
	}
	return nethttpmiddleware.OapiRequestValidatorWithOptions(spec, &nethttpmiddleware.Options{
		Options: openapi3filter.Options{
			AuthenticationFunc: openapi3filter.NoopAuthenticationFunc,
		},
		DoNotValidateServers: true,
		ErrorHandlerWithOpts: func(ctx context.Context, err error, w http.ResponseWriter, _ *http.Request, opts nethttpmiddleware.ErrorHandlerOpts) {
			switch {
			case errors.Is(err, routers.ErrMethodNotAllowed):
				httpx.WriteError(w, http.StatusMethodNotAllowed, "method_not_allowed", "Este método no está permitido para esta ruta.")
			case opts.StatusCode == http.StatusNotFound:
				httpx.WriteError(w, http.StatusNotFound, "not_found", "El recurso no existe.")
			case opts.StatusCode == http.StatusBadRequest:
				log.InfoContext(ctx, "request rejected by the openapi spec", describe(err)...)
				httpx.WriteError(w, http.StatusBadRequest, "invalid_request", httpx.InvalidRequestMessage)
			default:
				log.ErrorContext(ctx, "request validation failed", slog.Any("error", err))
				httpx.WriteError(w, http.StatusInternalServerError, "internal_error", httpx.InternalErrorMessage)
			}
		},
	}), nil
}

// describe tells which part of the request broke the contract and why,
// without the received value: it may be a password, a document number or
// another personal datum.
func describe(err error) []any {
	var reqErr *openapi3filter.RequestError
	if !errors.As(err, &reqErr) {
		return nil
	}
	attrs := []any{slog.String("reason", reqErr.Reason)}
	switch {
	case reqErr.Parameter != nil:
		attrs = append(attrs, slog.String("parameter", reqErr.Parameter.In+"."+reqErr.Parameter.Name))
	case reqErr.RequestBody != nil:
		attrs = append(attrs, slog.String("parameter", "body"))
	}

	// SchemaError.Reason never includes the value; ParseError.Reason neither.
	var schemaErr *openapi3.SchemaError
	var parseErr *openapi3filter.ParseError
	switch {
	case errors.As(err, &schemaErr):
		attrs = append(attrs,
			slog.String("field", "/"+strings.Join(schemaErr.JSONPointer(), "/")),
			slog.String("rule", schemaErr.Reason),
		)
	case errors.As(err, &parseErr):
		attrs = append(attrs, slog.String("rule", parseErr.Reason))
	}
	return attrs
}
