// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apispec

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7HxJb9vItvBfOeB3P8AGGFl2Rrtx8Z7bSe7NfUl34CG9iPLMI/JIrpisoquKaiuGf0yWd9GLRu96qz/2",
	"UAMnibLseEBw0StbnOrMc9VFEIssF5y4VsHORXBCmJC0/x6Q3qeRJHWyJ8QpI3MtIRVLlmsmeLATuOsQ",
	"xQUmEo+lezqCWHCgFPxv0OKUOKz9U+v8Z55OQziguJAUwgFmdMA0/f1ASxbrEGShEaINzNnGZHMDC30S",
	"rfcGfDeFmKRECYoUm/3BQYBikGL1mwsgBZPZ15QlGJo7sYNNEQyFlNgb8CAMVHxCGRpE9DSnYCdQWjI+",
	"Di4vL8MgR4kZaY/9HmoaCzl9k5hfzKCboz4JwoBjZl6N6wfCQNJZwSQlwY6WBTUXGgmZoQ52gqJg5sn5",
	"hcPgLcuY7iAucs0STCCbfT1nGUJCIEkVqcZEqF4QOqDOCpLTGqrUfqwJQEIjLFId7Gz1wyDDc5YVWbCz",
	"2Te/GPe/KrgY1zQmaQH7eTRSdBVkLYgAQWGqUS4DTbjPdcLWBKbfCcx7KZIi1kvZkVf3b8eNFSK/35Tp",
	"HrwVYJTHCNzu+zc/GKnnOKExJkJCKoD4ZPYbghKpgHnJrujkRLUhWS11ahEsw/O3xMf6xLCzH3aJsSSV",
	"C67ISvGPmOzTWUHKsjEWXBO3/2KepyxGg9XGZ2VQu2gs8zdJo2An+H8btXHYcHfVxisphXRLtUnzFkG6",
	"tYw6xkWWp2QIYlaVqAWsRbFIKIK/Q8T4BFOWHPsXovVecBkGr4UcsiQhfv/AvkqhUAVKJgywmhEnyElm",
	"TAkwhgBIaQSMY2teGpCPShg9zG+4JskxdSvdP9zmBjBOKieJiYCEUlAkJ8xIXIvCDq5jMm94YH8S+rUo",
	"ePIg9JXGyitLXzpnSlMTPC708ciAEkEBQkthzJwCg1Y8+23EYuEgPuJGV4RkX+gBoH5tDJiRWeeyRMuv",
	"tAS4aMBliXtZqqnVu91CnxyQUsyBlUuRk9TMKSXGMSl1bNdYtDD/+uXQS2AKzhtDtOvXssjuwI+EkqQ1",
	"IHMGIAzoPGeS1DHr+PQBjQtuTHVCMGEJWuFx0HiDFpgPoNHcYGe732GJw8A+eOyuXwTEjcn+GDiQgk8d",
	"EBWK5CqOvKPg8rJpuD+2qdRatoWk/369sBh+plibhUsXvsiBWBJqSo5Rt5xCgpoeaZZRF2FZcg0HUtrw",
	"i8UbOUri+pglXXwBkTFNPqjxkYVxHKT07CsQN5clzn77Yji02ok16WgfsVCFTbyvItgbnhdOxZKEGRgx",
	"fd+g3whTReEcSUu8K/EJ3qciI4NFEDb9Vhl5VL/DG9FqryZOjomkHvycMW20U0DEizSNwjkanhWU4Coa",
	"mjdxmFIZMlxNU4vsVRR8y5zHbdOIacra/1ylE+W3gstqIZQSp4sctl/rAqdyShVXLgKqHVXiVFsVoxGL",
	"maG40iI+NfwipXBsbv8k4ASnYG+AKvyDZEzIHmXEtYCxZAqe9k8dndooV6uttMcvSSNLF5BzH1iKnH9r",
	"UcMtcgvCM/sjYWNhnfswpdBIheJ4SscxKgqd3T0rXNiSlojGxlSeFbN/wwnGJDvNbkWw+SXfEVf4mcxK",
	"pHKc/S5Su4IiyAtKCDKhtEQJWEUkvZU6bbGrF+2izj8JU31yoFEXapE8qrpeGnBxGnxatax/q2u5t2LM",
	"eCPUvIHloMxzsBncPn3SMhKPO42EUr8K2TbL1cWWzXm+tdLkaOK4xOS8ynJJyjhkGhtR0BIVFBxBksoL",
	"Gyg+6W9D5D+hKKXYvHpc0i66udV2RGkg2UX0d7TI2Yqad+/AbHismOBqkUbv7U0bWqQgRep1qRTuAkRs",
	"8kRpQ2rBSXmDfPSmFXN8DGLUmIrxjiQ04ClMSe04v2VoUFnORQa2TGQYSJG2IhTxKycZhAEmmQ0bYlQn",
	"zF75FSWdiEJRZ/jSEoyV1PNPLyFil2uuv99+u3LapShYhNps6BQKwWnaYYeEMdXEISfDplikIhsy5EKF",
	"EItMWDuXYWoeceDC2gla2S5vkVpvMSvY3Hra7/f6fSunWpM0C/3vYJBcbIabTy7XBoOe+/Hkcv2//tZF",
	"Lp/VL4J7xMFn9C7FiVHPvqZiLHrwKoVcUuwyN8bjtJgSvPmw+wNEuWQxHf/K9MmxxvMI0uqBECQlgidk",
	"ciaErRqn3oBHsVA6gilEGcox48c5yZi4jlzirsjn8RyMH2DEvemmhBmRboJncgQvwb9KpsnWr4JwIQPQ",
	"bNIUkKEQKSE3JBmi7HZezSiR0po8Zf7a6ZeGqOi44Eyv8sFHnOmfR+8IVSHJvFnWt1ZGrF2wNOKva9i+",
	"MDAMWJkjWMG+DL8pem+BfyU2NuKeYOxB/1Yz2pakDn1EOTaqJoaSgCqRNpkZcY02NMmFfRk/Uw9eKeA0",
	"Rs0moiK6fcMBnAsJCQ3xs1cXobSYU9ZnvWfPnj2/mck3+nRtvrS179qvqdOinTgcHv346P2HvUebW50W",
	"Fs+PJeqVYB3i+b55rNPomjUrA1vrSInxAi6NZcNSe1emU2XJ8huyqaVGoIxgE4IhSokqhNmfnMXC+1Ny",
	"sUoPPhgJFsbx+vRIsZalqMn9/Hl/c+vxk6fPnr/Y7rfjpmdP7tOk3DAHu6GVmNP4duW0f4UWNASxGAp4",
	"/2HPqJrrM2xubEFepGNM5rLaretktTfSJq8W3ex31T2xjPkHBOMCpUt7M5zO/lRxkaJqM76lZ3NcX4HK",
	"bZVwqf5ZFtdqWK1zhX6993nXbXJt/6muOFILjekVTRB73+hj6QSVze9c/dv2wUYs1VKEoBiHHMeMYzOH",
	"bDY5FrP6cv0u/PcJk+n1MzwTUU9vleQdsDE/ym+Z5dXyhxz/m1ItJGdpKnqxCMKb5oClzrZ585PIjFc1",
	"jjApaPb7nCfc5Qj/mP2R0Zeb6zDvatX99ObQ9jyT2W9jpr0Tl2zEYiz7By+2+9v9x9uPXzx6Ec1F0Y1b",
	"8/C0wNlakQPPJa1cS4IXMIXnWxCjxFiTJNWKxq6VLL9YneUsoX7TJLUwfk1Skra1QRPNH3oJuCk35gR3",
	"Lnmy5mQuhboymy5t1QJCh6hs9/XNh12XKo1k2Rgqk6a1qN/b3I6AFGxuw/9fDyEjLqS1BJswtdKxkE21",
	"iWI+0E6k+tdIoA4t0j9Xbm7OCN4q5V9aSO6kngXkoKx97FcvXty6IljK2/XNeYsqq8qnDqB6kS7s2qFM",
	"R7ZqXYFxZN4V+xJfXBDXCFPz/4R4Qs1syfLfG2fTlAuDLAiD03EQBqktUHxGl/Zb1RgWqTZ/x5gK3m3G",
	"lem4MT09MGTwgaTty5j+Uf3rdSkP//rlsOwu2yTU3q0F5ETr3HXJGB+JRax337+xZWDbrg4NZgeIB+bS",
	"mJS2+mGLQPk0s2n2gO8JPiHuCkA7A/4I3goFxJNcMK5tW4rTWJisZsImxMHmM2XX3CTolm8kiUPBfZPO",
	"dZ5g7V+/HK73qm8anpICxawBgkKhdcWkzgrKECIrYNEORBcDJwCDYAcuBrayav4dBL1ebxCEMCirrI2r",
	"l5dRb8ABfDuQVFlQhimYGqH5zyRk2ezrWcE4/gCR/0hUd3SqavD0ylqwwehVCgnjJIX5PiqIfexhWpMM",
	"PyN3ZslJgqoNDKxFg6pIMwii9RB4wWN0j/PZnxlJoRzR0Icmzq4VCiGysyQRrLkBFAGb/f66KZK4QY7I",
	"v6dgRPEJKpgYEnPYf70Hjx8/3rYZ7NHhnqt/aKatlXPCYoYlgjCYkHQdUmP8en2jaCInjjkLdoLHvX7v",
	"sTOIJ1aUm8MTG6mpN5uruc8J5jJ65iYPpCRHND+FoGj2u/mf8ZglZOGdoGSoSkelQnADFAnZoq4x3ClC",
	"yoztTmjAy+d+aPYIJOVMW39XTkD4Eaioqu5FvnwsHD2MRbTdXDPQ4qrnfnCFlP5RJNM7a3a3KvOXbeNn",
	"8qz5kZGtfv/O1m62wTva7Qc+q2KcxQwTGyW0B9Ae1XM4Xev4hzcWRtXsYk/6/WUvVhhvNCZk7Cub9z9l",
	"sOfEUrRkknErrTZ/6BiUiSUlxDXDVEXrPfhJgKQJpehrQV7S3ZxFz2Hy+EFGfqhsjli7pgqVE09Ml6SB",
	"RNkYcTf9wIQBcfvOQFwWfnQCrcCRM2bWSirBy9FB1WERujBZbPF4lLa275/qL81tZmfumF2nLTJaiOMM",
	"+bQcrlIu4Wgo1j5pOX20O9JuMGPJkIgJYUzr1/x140YSkGuyftotjKboCLygiQ1mFsYr69zWYPH0OvrY",
	"nqdqRjXBzsdPYaCKLEM5DXaCN9ZqVDOhtlowVnZ0xIQ7n8y78z5DFHq509iniYhxcXLVZTJ+oHRtCqqA",
	"EWYsZWjcoR0vrR+wlVqWUJYLQyHqdRl7A0Z74PRjN13qRzbmDNynBbP9pIuXzsDa6dk7t693zM+91ojv",
	"anZ6Ji3n5x6aDtcKfpo4reDCCTFMgWwjoOCtuahaxNus9EQpXdyds/TBPbEkLib34Yk3H2p4r+JsCGKR",
	"9a15vhBsMjL7AwSMCgJJhWYp+4JJ56yqcuSL1u+YOHesRvuWhbIxHb9alRQb8yK/QpMkYaOaA2vODxrz",
	"p4pqkNbV2kIgH9A1QFhUHVdLvKeYt12ovFbQu/lQqlZOk8SSMMEfGkTyk2rfUTS8tXX/arubjmd/ckjQ",
	"tY/93LhJcyWNUxt+lRpoy3hRWKskZ3ru53F8QvHpccLG5taAR2XJ79iERepESPtG62oq+Lj5mUYhsXm5",
	"UCTdRdvTvw/NHTM/LsMrXbtSeX1DzVfWxl2bNQ6FiWpd1aBsyat2cTYEIRPiaB407pDbAq4dtJh9lUOR",
	"giJAmdkkGqJqODPqiG2Y0ns1UPfo0FqTlsui/BrjXiO7u5pfrYnzOpG6+qV658ItxKISBIMTyib4DSnw",
	"4yWmAnj+qB4GCnbKO2506jKsbHmbRXu2aV2S754McHuS+IENcIVbV+5d0dQbYC8Y31opuG9ZehAT/Cr1",
	"Or+w36EqP5Sde2f/XGhl56/b2zuqx6rtHeu9O1EJI7XOLtZacSOlsNNYQbfx3LioN/NdOhOaUlcn6MCP",
	"g7lqrc385oFyXd6qFcwZqGLYMkTzNvOlXaylkKvyuoYUWyC+fzHuP1n9RrU76Y5rQ1eVrxqM85vAKtaJ",
	"Oc415ZtxEw7clXD/2CVI3yLdN01AG5tcTfbp55SWZdHeRkwr3e/BAWsFBNfaetGW/qM8+S7dUf9B3FFb",
	"AjHWBdoE9D9Pn79LPxZe343Vjw44mYAaMqayFvs6lnGqUTrMTExYxuyeGduTt28VHGIWp6K5bjyN09un",
	"GZV9eeXmlO/Ue2a0NOVo7K3FwrCbxWiqLaqoCgimbqDKDbcdPvEfpN/RfaYP72jFruAG5N+eO9yac0cl",
	"NNYyXJkLese1PBO0WQWkQjV8XHtIB/ZMfncWwbBQMTZyQViLMUHIMcWhNH3QIQEa2Y5J2rm2AWdZLqSR",
	"Ms1S05jmrDl4aBTAfO7gf45M32t+iBXoHA08oZubwJRMDMUykqZdap3MWVSmqc0ctauXypR+X9JiwSHO",
	"Jcd0rgWgw1e253G0Gf7MJ/GS0wzOlu3L3+zalx92RpILvLB7idqj811rN+dob3S6wcKunWpxO9Ns+khu",
	"kHxEsRbrITBe3hCgxRXnTvipwc7DHeqB6XLapbrAePUvpmnnVMvKIMadn3GNB/15FvdaZ2/OpHYYmCMj",
	"vrOvZtCiNTL6nbv720e4VsFqfO+8nuHpfk/xY2uS/4GrGSVmHdLkbwlXyhCw5pR1/bsPHrcfJBZ0zobS",
	"Dn8zRR/t8fboPKxF6rQ41nhK3NR+/T4Mf2G992Ch7A2q4uq0aJapPcjNS17tfEV7wKsbjTXbz7O49QG7",
	"P67xuxzLN9c6az53FLiWVZ/KcNwyaPWfURsX1XFBl0vjpZc0KSidtEY2AQvu5iH07N+Vd+yMX5sW6X6d",
	"zRLxr8dM/7NSyVtL1Qf6dpmqfNGN6iz14VVLyyz7RFme4hd0cZaNDY32K7fLdGjmxRtbXxNqolBJIvBG",
	"fTK2lRu5rObyvbnMh9aLRrlF/FU+/cvFLrpYo4OmyiNUiZ/N0uJ5r2SyW+X1bfZHvTd3wJep6VpU+mR/",
	"6T6qPffpNTcs1H67zK2MYefASVNNK3tmN1A0Jg5XTtrtehi/G1ccQhkw/OWSWzLrOHXvQpvQw4ltQp8R",
	"Kqm1pwuRdHbC0ENOsD7mjSktJMN0tUi/rDD4joS6joP/EuuWWL8khXcn2Sf2SKcvV9XdcyliUuWhEBPD",
	"E79XgNk9jHb+nscMu2vu//Qr3KNMtc6lWipYFolyI07vyqmpt2anGKlmSckRypfH7bbn5UR7i6pFF1iz",
	"u/gSctH3egUFd/uIGFcazZPeKRlHP2QStJx9NcdWdtJ138Fwj2Rt7gXv7jPWgDvhsFuafP/68YNEWwVv",
	"iaAJukrizh8NapkWrV/NeYMzW8r69ovtnZAfPxkbboxwd1/A6K20Gy8hFbFtvBQy9VsidzY27MUTofTO",
	"i/6LvnUIHoCOCvvQ7ZhIvZzaXYwecK+c5Z7GqucUlzOzvrrusVos4PuRQWuDmc8Ly2nSafVfQlVfy27D",
	"fNU+9dPtnYSkkAibTyFjvNBCwbQ++MhE8MsOIYVXc0PWA243Jbqzk4jXE9mLB4V/65ng4YBLoS1YtjFV",
	"KOFGkasRbktBiBlJaTNqPwNpKGJPH7PNFiz3cbg+kic2Fp2krnsl0+WjlL3GXk1HhcbOzGq3+BRoyRlW",
	"LUBK53D56fL/BgA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
