// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apispec

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFrNbtvG9n+Vg/n/FzbAyLKdoLGCAtd1ndZF0gaWgy4iQzweHkkTkzP0zFCNYvhhsryLLorsutWLXcwM",
	"SZESbac3dnBXEj9mzvfXb3jNuMpyJUlawwbXbEaYkPZ/h2RPaaLJzI6UuhTk7iVkuBa5FUqyAQv3IeYF",
	"JhrHOrwdA1cSKIXyGqy6JAlbP1ub/ybTRQRD4oWmCIaY0VBY+n5oteA2Al1YhHgHc7Ez393Bws7i7d5I",
	"HqbASWvUYMiI5WcJCoyAFOtrqYAMzJefUpFg5J7wwJshuFBaY28kWcQMn1GGThC7yIkNmLFayCm7ubmJ",
	"WI4aM7Kl9PeIftqUrQevFDglOsKHb05eOOklzmmKidKQKiA5X/6JYFSqYF3CHouYcHsGllnEJGaOubZa",
	"W+xn+OEVyamdscFevx91iaPJ5Eoa8tL8gMkpXRVkrLviSlqS/i/meSo4Oql23hsn2nWDzP9rmrAB+7+d",
	"lZPshKdm51hrpQOptmpeIehAy5mFF1meklOIo6rRKtiKuUoohu8hFnKOqUjG5YJ4u8duInYiLWmJaSDx",
	"6Az7ByAkmZw0JgoSSsGQngtnvRa3ga8xuRUls2+ls6LS4iMlj8/rS0wtOm2GoFItz2+ptmjw5Vm9qRzI",
	"e8RhYWdDMkYEtnKtctJWBHdBzsmYsaex6fu//H4GLlgcGyFfQHxY0vLCDuAHQk3au/aaa0aMPuRCkxmL",
	"jq2HNC1kogwkBHORoDdF4KYMNeY2QOdTbHDQcH1nmylpR8C/OA73rxnJImODdyywxM47OCoM6fss8ppY",
	"iKqrQmhn6XdtLbXItoQs918RVhfviVtHuHbwWqRrRiunT4JgpphMBBck7dhYxS9ZxDIyBqfu8a8KZrgA",
	"/wBMUb5IToFHlJG0CqZaGHjWv5x6CdqWrqnd640/kkWRbighbHCrcOWqDQ8Lwm0UlOXnREydR1u8SCkC",
	"kmAkXtKYo6EoeN1VEdJJWgnKnaNcFct/www56U6nqxW2TvI1SYPvyVEik+PyL5V6CoYgLyghyJSxrvRg",
	"CoUpUAvVQWBNKV66FdEu7fxMmNrZ0KItzKZ6TH2/cl91yc7vI1uu6iL3Sk2FbJQATBLhNIDpmwbhCaaG",
	"NlwkKy3YLDrPnkYsE7K63u9QeY7G/KG0T4oTpTO0bLC6GTW3+26vtdtux26WJEo7FsmmCY+zXJNx6Yim",
	"zhWsRgOFdGXI5E5ghKf9A4jLLQylxN3ScaU7n6dqFotCJPdaOCilIWSX0l/TpmVrbW5IKNqa6majag46",
	"1uekM+ETutnU0Rv/0CfWFLRKy1iqnLsAxYvUOjfnXChJxgVEivD2pJVx3zGOFlM1HWhCx57BlMyAa0Lr",
	"/VxYykwne+UN1BoX7lqrtJWf1R+SNIsYJplPmhzNTPg7f6CmmSoMdSbvlmPcq73y7VuUuGbksEW9f3t1",
	"aYmodgUvUNsMXU5xSpgsvjzunZ4XXxX6QzGVb/OvjP3aAxhK/BelVmkp0lT1uGLRP80MlfbbLvqryi40",
	"eQdNClr+pVqexw4lwk/Lzxl9XCPY77cIdiUPKWwHvZMzP6kkyz+nwirfcpAWE8GR+6FiK35+0D/o7x/s",
	"P3/yPN5us9N4tM5Pi529ezLjWiqTVhM8hwV8twccNXJLmkwrP31RCn1+v+/fon0X9RQyalvil6Q1WdJu",
	"kDlO4az0gH9qjTXHXQspYTcD684ce+bX/1aKsR5PX5dTu9KBf/V2RoZVcTmtF15/dctVmS6IVGXYu5a3",
	"tLKRfDtbuBWRTenc6OBmdmEXQ0chCHLhO2rX+a+uXlaq/uX3s2pidTuFpyvdz6zNw3wj5ERtuuPhmxPf",
	"wvoROHL93hBx6G5NyVgfnr6A5YuMTG8kR/JIyTnJULwGI/kEXilXxJJcCWn9QCFpqrhQMBdzknCB71U9",
	"icew8EOrIE0SClmOV2FmgK1ffj/b7tV7OnWRASN8mEBh0MMdZK4KyhBib7t4APH1KOh2xAZwPfJdofs7",
	"Yr1eb8QiGFUdYuPuzU3cG0mAcpAjUzXDsADX37h/udKQLT9dFULiC4jLTdzLdvmp1cku7uxjnUTHKSRC",
	"klZufzTAUVqRYOKGSoHvUQJXmYIQEsZ325mr+bAVj9ju3rN+v9fvj1i8HYEsJMfwulz+nZFWJigNIcep",
	"kGVaLQxCnIpM2Bi2suWnDyJTsNvvb8MCYjWZGLJxuc7AhPgMDcydiiWcvjyC/f39Az8YvD07CqiOFdYn",
	"qOAsDoBhEZuTDrMt6/d2e30XBConiblgA7bf6/f2fWaxM+/KTUBmJ3W9srubK9NRN4YioBlaU1BaiWwY",
	"Wv7l/gvJRUKe3zlqgaZKpyaCAMok5BtSV3xShFQY6wbdkazee9GcbzTlwvqsXKEqJbwW151JXLa+KujD",
	"JRs/h58kDo7x0oSIJ2N/UMniwWCK1lRx084rVhe0DkPt9fsPRrsJYHQAJcMSGRRScIGJr2VtcPPJCtvr",
	"olO+vLMBg3piT/v92xbWEu80UDe/ZPfx8aGj4Jaq5ZNCem/lVpku8I1rSkhagamJt3vwqwJNc3LoatPT",
	"6YMwlnpBkv1vAiNSNdj5vGYKk5NM3ITXEKIa6sLDEupyLB48GIu3VfZOpg0EdXLhs6RRsoKlTUdG6JJk",
	"czwtRdo7eHyt/+geC3QQnPB02i5jlRpnKBcVYGtCW9wIrFOyevHkcGIDpHYLvOcQFgdbud8Au2pAacnX",
	"6UAYtfsvC5r7QWADuq8BPy/Fsy+Jxzau3Oxq2ODdecRMkWWoF2zATnzWqM8bWMQsTo0H/Vy7c+7WrtcM",
	"Vdjbi8YpzRXHzVOR0G+XhxVbCzAFTDATqUBXDv3RxeqFHhwbEAlluXIaol5XsndstA8z3nXrZfXKzlqC",
	"O99I20+7bBkSrD+ZefD8+sD2PGodH91vztJIt9vzCLMLcZ89XZ9WSBWcGBZAmavkhWwh2isXb5uyVEpV",
	"4h7cpN+8EmuSav4YlXj3Wx271JaNQG2avnUSE4EfRpafQcGkINBUWJGKj5h0nn+ZoL54+4GV88BhdOpN",
	"qBsnr/eHkhFTWeR3RJImbGAOsBXqoEt/pqhGlRIRioDKhq7BwmboBMTrkXreNpz2RU3v7rcKtQoJ55ow",
	"wRfNE/KrghL8X+qG9/YeP2wP0+nybwkJWtU4i3ZjrqZp6tuvKgI92BRHq5CUwq5djvmM+OU4EVP3aCTj",
	"Cpgau7bIzJT2K1p3UyWnzW0acFfzdmFIh5sOZ2CPEblTUUL9so61O4M3IGJT6gjZ4xpCACyc+QRHl/JM",
	"UUexC14DeXnqsBmiP5F9TewRi9Jr6gyQTs57jfHsboW3Dvu/wkq1Xd5W3HBbYNptkJk/Kvx4lzlyrTgZ",
	"VU5KczFX1RwnjMMW/GzkZpJuU/xcUnhEe7TOO7stUwlRgSS9Oz36lUPxyJiGzoKiSq35g5PbleYmtaZe",
	"YOsCjce/XbYw2zUXMmA8QhqL7s0STtPExYXQYPXy00Rw1anX08DDI6q1eZrUPUSvGA/O4eGmXnDe/W+S",
	"gl3GaajaZeIaB2v0QlLZsTdavH235Z3M4lbTtxe2Uep3564Rdp/2VF30+vRrUGuVpgpSxX08Fjot4erB",
	"zo6/OVPGDp73n/d9V10ysHHeqtVFmGbT0k89wlwyXgZnhTfXqYhX/Uz5BVgp1U20OU76dK6iUNH94VVV",
	"6Rf1v4TqdOch8uP2tzQB14ak0Ai7zyATsrDK+PXVB2skb/20B47XGuCR9IBx+MiN5Kpb3vxA8L/9FjAa",
	"Sa2sZ4tjglAYFdrEur0OEDMXpDWCVQ51cXXeacSfaicErjyVM3bAS0tlOxLs5vzmPwMA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
