// Package apispec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apispec

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1Lc9tG1uhf6cKdWyVVwRQl24mt1NRcR3EmnnESj2Rn6lboKxwBR1RbQDfc3WDMqPRjsswii6nssuUf",
	"u3W6G48mQVLU6/OkvJKI5+nT5/3CRZTKopQChdHR/kV0hpChsv8eoTnEU4X67EDKc450LEOdKl4aLkW0",
	"H7njLEkryBQcK3d1wlIpGObM/2ZGnqNgW98YU34v8mnMjjCtFMbsCAo84gb/emQUT03MVGWAJTtQ8p3J",
	"7g5U5izZHozEs5ylqBQoplHz2e+CSaY5y6H5LSRDzSazX3KeQUxnUgebRnYilYLBSERxpNMzLIAWYqYl",
	"RvuRNoqLcXR5eRlHJSgo0PjVH4DBsVTTFxn94rTcEsxZFEcCCro1bS+II4XvK64wi/aNqrD7olOpCjDR",
	"flRVnK6cf3EcveQFNz3IBWF4BhkrZr984AWwDJlCXeUGMqkHUeyAel+hmrZQ5fZhXQAyPIUqN9H+3jCO",
	"CvjAi6qI9neH9IsL/6uBiwuDY1QOMJkCAbMUBXl7wc1Q8P3pqcZVOAjWzoBpyA2oZUiQ7nG9WOgue9i7",
	"7FdKZlVqlq66bM7fbNFrmOuwyz0D9lIyYlMi7WevXnxB/CVggmPIpGK5ZCgms9+AaZlLNs9DDZ4cU3Ro",
	"OGDcAGEFfHiJYmzOiHCGcR/DKNSlFBotv3wJ2SG+r1DbbUylMCjsv1CWOXd0svNO09IuOq/5i8LTaD/6",
	"XzutGNpxZ/XOc6Wkcq8KUfMSmHLvIsZPq6LMkRBCb1VgJNtKUplhwv7KEi4mkPPs2N+QbA+iyzj6WqoT",
	"nmUo7h7Y5zmrdAWKSwLWcBTISlQF15KRyGGoDTBIUyvIOpCf1jB6mF8Ig0pA7t5093DTCcYF6hIVZJJl",
	"mDONasKJ4gIMO7iOke7wwH4nzdeyEtm94FeRPtEWv/iBa4Nd8IQ0x6cESsIqJo2SJFA1o2Wls99OeSod",
	"xG8E8YpU/Ge8B6i/JgFGNOuUoww0WEDAVQcui9zLmk0t3z3L3lXaFCjMC1FWDtws4/QayF8pWaIynFj0",
	"FHKNcVR2Dl00EvyYZ1cQWnEt+656+fuKBLiZrkPTER8LzP5VX21lC3hE4wcg/o72oy+r3EimpCFpR4Lw",
	"RGY4hijuCqvHXrHVv3f7RG8rtn/sLikO8NEBv4HnbfM0efIOU0OgPqvM2RFqzR28IYIhTVHrY7vLizL+",
	"H/9+7WVAzpzlxZJnfrctHPvsSwSFyorwBfTih5Ir1Me859FHOK4EKcsM2YRnYNnXQeNVShS3uH067NGF",
	"cWQvPHbHLyIUpDR/jBxI0dseiCqNat1mf4sLexBgKXhtsEj//L5NqM21xR1IFYLB7BhMQLIZGHxgeIF9",
	"iL0ieTsterF4ogSFouaS+X1hsuAGvQHrrUhS3ajN7BdP2Qpmv/1MO7TejOji0V5ioYq7616FsOtIjXrd",
	"LWu+ymWBtIqQGXfXMuNKXB20yCkhUzhg3xfckHyULBFVnifxHA7fV5jBOhzSnXCSY220rcapXewqDL7k",
	"zuYJccQNFuE/q3iiflZ02bwIlILp4g7bp/WB85VMK1IDh3jaA83VCPqci6zL6WWl0jPQGMWRhpz+GAVC",
	"n/Zy/xyk9lmWlfqgbYyYhoYuImwNm8wJIl2dnvKUE31oI9Nzoi7UGsZ0+jvJzmDK7AmmK38hksA7QMKE",
	"ZGPFNXs8PHfQhShp3rZWf3+FBni+sED3gKWL83ctyiO7uAVSn/2e8bG0xuBJjjHRsBZwjscpaIydlnhf",
	"OTM3rxeakmB/X81+ZWeQoupVEg3C5l/5LQoN75DehLqE2X9kbt+gkZUVZsgKqY0CxaCxYAdrJZBdXfvS",
	"Pux8g5CbsyMDptKL6NHN8ZoI5fl6YvN39b2u9mL7dLPhk64AP5EyRxDRZSA970lrrBDlHtC1Mr1x2G9F",
	"pn9prStWKi5SXkK+qWi/qhytob4NOdps9vXl6Es55qLjym6AQyw8x3ed58ePAjw97FWBWv8kVUg+zcEA",
	"7Z/vrVWoBgUsUajPi1KhJnMTxyQ6jALNKgFMoS4r64g+Gj5liX+ExhxTaw7XqEs2t0kcUjqL7EP6t7i4",
	"8w02b988s+635lLoRRy9siet4ZwzJXMve2thWDGZUhxKWZddCtTe3HjzIrCof4xSMJDL8b5CyLwC1fuO",
	"gwkHDT0vbmBAuHGkZB7Y3/IngSqKI8gKaxSnoM+4PfITKDyTlcZe4zwgjLXY81dvIK3a54d3N3KsJgW7",
	"oHAbeolCCpz26C0pnAdYIm1TKnNZnHAQUscslYW0erGAnC5x4LKtM7C0XZ9CvR1sVrS793g4HAyHlk6N",
	"QUUv+n+jUXaxG+8+utwajQbux6PL7b/9pQ9dPmq4CO4bwbyL6UIoKZjZL7kcywF7nrNSYeoiQ1ykeTVF",
	"9uKHZ1+wpFQ8xeOfuDk7NvAhYXlzQcwUZlJkCJlkwPbaNQ1GIkmlNgmbsqQANebiuESVojCJCwxq9HFC",
	"wchu4Ci8qseME0l3waMYhKfgnxQ3aCPxUbyBDj0B1W/sdH0gzFv01PGxXjvmBDQeV4KbdTrgjeDm+9Nv",
	"EXSlkO6sI/Vr/bE+WDrexRVkXxzRBqz1gC1hX9PKCMBfuRrrT04g9aBfV4yGlNTDj6DGxGryRCHDhqQp",
	"7oDCgDVlS2lvhnc4YM81EzgGwyeyQbq9wwFcSsUyPIF3nl2kNnKOWT8bfPbZZ59vJvKJn668LyH3Xfk2",
	"fV6FJtTrN18+ePXDwYPdvV4JCx+OFZi1YL2GD4d0Wa/QpXc2ArblkXrFC2vpvPbqhmWdErmGXblUCNQe",
	"T4bsBJQCHbPZH4KndXAPna0yYD8QBUtSvN751zyQFC26P/98uLv38NHjzz5/8nQY2k2fPbpLkbJhhGFD",
	"KTHH8WFmZriCCzqEWJ1I9uqHA2I1lzHd3dljZZWPIZuL2exdJWazETd5tujffpc9kMs2/wjZuALlgjoF",
	"TGd/6LTKQYcbH/DZ3K6vWcpNmXAp/9ktbtmwec8K/nrl/fSbeED+UX12pJEG8hVJVnue+LFWgtrGA1x+",
	"zWb0T3lulIyZ5oKVMOYCujGHbhJ10deq39+3/n918gRLgHN0UQn7g/BstUMN6fUtv73B4+sbfYcI2fTq",
	"kQxFl98omHGIKfLyvznV003yEKccbyAKr5W5aV/Sh1DKPL0pb+jut9QEAv4P5kYqwfNcDlIZxZsGA2rh",
	"HfLBd7I4UY7mswpn/5kziZ4JYH+f/V7gz5sLc9FXffLdi9e2jCeb/Tbmxltzip/yFOpE9ZOnw6fDh08f",
	"PnnwJJljqs6peXgCcPbWBEPmohfCKGRP2JR9vsdSUJAaVKgDs/xKUZMn693dJdjv6qZgxV+jUmhsCoTc",
	"uteeAjbdjTkKn/OirV6Z86VXhlXm8qrLpSttteZjIdmWt82BzCwNOW5fX7Y+eBiK1gd/20S4HlFg/yVO",
	"sEdnvQSf6Rcpt5VRVcfLRmFjWhozHLCkFgUJw8bx8HUymnf20xVlGOu1ZKhIx42ETS4MWAITVDDGY+de",
	"b9EfSS8sMOO2MCezNRJOM7744dn2nL/duNvOp5zzrHsd684br2xpfaTp/GvI7V5qbgjiNgyl9mk3spVa",
	"Mrw3a8lC/q2c2CRXb8CpkBNecJsCI41xDirDD/O8UErNa0ZHYRSwKZtn/gFLGv2ZsOlIBJxwDKcG1fLY",
	"Uj+xs0ThKSoUKSZ0VxOwEC6hl/lEplzHFu71V2aOE8hBpHi1uxYrUq7II5uyoEzTSqkNY0D/A2U48zFY",
	"G74h4gKqP0LrqbmdJEvdhs9tnZXhpatWXYCqoYJ1YHUz2w2rLiapXYUIUe2xrIyNj9elUZ3EtT/X/OSi",
	"v5BlQ9PUlab0Rhj/VfHZr4IpHHNt1Ox3Eg0tg16zyGOFDLV3ByZwSPktqCH1rRU1tyZ16wfeSPC2KLw3",
	"wVvHABagew3aWiEvfnjmjKVTVRd01mbTVjIc7D61gnf3Kfvf2zErUEhlQd9lU2uBLdhToTlFDwgNquEV",
	"zKjX1ob8vuzPgd9RzroXexaQozqneNjceHHjyozafL86HQZYWZcsdgC1L+ldnRco13HNT5Usjj9C/9zI",
	"DaFaZegtLHLh+WvMvxrDh7YRoIeUxcbCR1Zmw3vmVuiUCe8vDA2jxj12WhvLctEtX32TVigMWWPaOyPd",
	"xJQVCV7zVbbCqoji6HxMasDmgt+By7Ba5/OESmajOBpDLkV/5EljWilupke0YB+ztwWeVIja/vq63vl/",
	"/Pt13Shg8332bEsKZ8aUruCZi1O5uOpnr17YCi3beRDTyo4AjujQGLWxItPm28tpYTOaI3EgxQSFy7Xv",
	"j8QD9lJqhiIrJRfG1rcKHEtKIE34BAWzqaO6AYJyoXbDUFm30NdbuxJWtvWPf7/eHjTPJDZHzTS3LiGr",
	"NFh1gvp9hQWwxMqcZJ8lFyMnE0bRPrsY2aIn+ncUDQaDURSzUV0A1Tl6eUl+HmO+sht1XevFpozKMei/",
	"UiqqTn9fcQFfsMQ/JGlLQ5tCrenKMi1a0fOcZVygkvR80Cz1GpSqzDm8A+E0laME3eoctpWMmnz4KEq2",
	"YyYqkYK7XMz+KFBJ7ZAGXr06VVdpYIltQErYlutakmx3ONymfLTryUn8fZqdIhltbEIoFuzw6wP28OHD",
	"pzZZ+Ob1gTP9DTdW8Tliob6XKI4mqFypNenDwdCycYkCSh7tRw8Hw4EPOpxZUu72wezkVNpDR0tv2M0l",
	"T7lrIlEKHdJ8Q4nG2X/ofy5SnqGFdwKKHD4fOtAxc70wGdr6GdLlObCckzrPcCTq677olu8pLMlczttm",
	"Ft83lzSFFImv1PGuEEm7piPLFSr5HiTU5kuZTW+tbyEogroMpZ5RFc53/+wNh7f27m49fU/nxJFPYHHB",
	"Uw6ZjcOFXYsP2paqvvf4i3cW+hvtyx4Nh8tubFa802l2srfs3n3DyIEjSxnQJBeWWm2qpqfnKVWYoTAc",
	"cp1sD9h3kimKd4BPu3tKdxGMgVvJw3vp3qpDbk6u6UqXKDKeQXcRngn8Sd/7QiA+vTUQl1mkvUBr5tCZ",
	"cisltRR1v6nukQh9K1mspvNL2nt691j/ik5z2z7J7XtCkjFSHhcgpnWfnHYh/Q5jHaJR0wfP6uDJkm4T",
	"MmEoiEN/XeeYYiAMWj3tXgyK/hcVTqwxs9CT2/pntIrHV+HHsDWua9VE+z++jSNdFQWoabQfvbBSo2kk",
	"tonZsbY9KGTuvKV753WGtxL7lcYhTmQKi+3OLlfgu5C3pkxX7BQKnnMgdWh7ktsLbFEMz7AoJWEIB33C",
	"3tma3S7lH/vx0l6yMyfg3i6I7Ud9e+kErG25vnX5esv7eRD0ha/fTr9Jy/fzAKiYcM1+kp1WCemImE0Z",
	"2sBXJYIGq5bEw630SKlV3K1v6b1rYoVCTu5CE+/eVx9ms7Mxk4tbH7Rmxsw6I7PfmWSnFTKFleE5/xmy",
	"3rZj7dCXbN8ycm6ZjQ7tFqrOSIX1rET5wqpcwUkKoZtf23J6kMSfrpqeaJfNjhl6g64DwiLruGz9Hdm8",
	"YSnAlYze3ftitbpwP1UIGXzRQZJvefuIrOG9vbtn22f5ePaHYBm4Sl0/AoDcXIXj3JpfNQfaRHkStywp",
	"uJn7eZyeYXp+nPExnRqJpE6qH5NZpM+ksncER3Mpxt3HdFL13cM21G4P2vLpu+DcMfedCaLhtZXM62sX",
	"fdRs3Dd347Ukq9ZFDerqZx2WP8RMqgwF0IWkDoUtkbA17bNf1InMmUYGqrBONEuaLs+kx7bh2hy0QN2h",
	"QgtaNpdZ+e2KBx3vbvV+BcMDWkdq9U3tEIobkEVDCLQmUF3wO1TgU7AUAfzwoO27iPbrM65L5TJuZHm4",
	"RQe2PrhG3x0J4LAl+Z4FcLO2Pt+7wakXwJ4wrhspuGtauhcR/Dz3PL8wuqIJP9RF0k7+OdPKNnKHkzqa",
	"y5pJHduDW2EJolonF1uu2IgpbMVC1C88dy7aCVCXToTm2JccPPLVES5aaz2/eaBcprKpuhWc6eokEETz",
	"MvMr+7KAIdf5dR0qtkB8/GQ8fLT+jmbQzC3HhlaFrzob5+f5NFsn53auS99ckDlwW8T9ZR8hXYe6N3VA",
	"O5PRyPv06c5lXrSXEdOG9wfsiAcGwZVmOITU/6bMPkp1NLwXdRRSIKSmAuuA/vn4+aPUY/HV1Vh76Ugg",
	"GdSs4LoItq/nNY41aoXZqeWz2Xd7VyVYytNcdt+bTtP85m5GI1+eu5bQW9WenDK5RqrpTlubpVdEEKRS",
	"fOy8jrba10mGOp3JuMh4CpQ7aAsaqwLitpZRoTaw7YN2rHCla/Ik52MwktKl7AhHtAlSAWVR56p7p7TN",
	"uWSplWl9mTg3g+vITyi5C1k0P+Xrno3j+SKIPibq0KkvdYNMfjKUN4pVNPW5MUtaDjl2VZht2ohCFIun",
	"w6jE/OgcOlrX47QSKmZJU4HTOToS7WEuXJfo7UmWbsjCl4+67JDtF1ZcdqRMIzF65Exzbt8hY4moUa5n",
	"aoWcOaoKCGQKzIkcF/nQZL9TOUkKOTUhMlyQFU0nAFk5aoLMkNCg8k8/5m0k2mX6oF3eJ1Jso9cE71Km",
	"BL1knwTKn16g1Mfagv5+kdBl/n5JcbciAVw3gh1ZyApUKYg0ND1uQSjU9d+rpAKkoVToSIEMmSTTRLg6",
	"IQuwN0zsWW24oFSRtSmyPquCSufdIwYjQdVnmdRBTTPhEJRB0ZqNdcW8k0hGgc6hvzaorpW8S/kRVrze",
	"swCZKwbt85J6cEpIb9D2SZJcV5JoKLCt3K1ZaZndMRJ9Uobdv5B57XYeVEeqWNZFy9T6NiRMDf5Vciv2",
	"pbYYJMPxYn7FLh+0nQ28JNvSm0p52YBwh/GJYGjbkkyKXd9/Yw7letRwlQxKjbY7K9vsDgC8Z5HcrK23",
	"VCRDnzthW46wtz/6aNU9BJP/b+1mNB3LrghYYx2U2urISRK7Bs6bifAfSXwsAPD2czeElSsyo0vC7xcg",
	"YIz9cnnnov1qxeWOVVFLRTWZEOEslDMQzKCg9XftCmekEaCx3T9dtVbjdM7yG7DuRDjbZd59lJAMSlCY",
	"ItvSVRD30ixFJbd7a8F5G3+ai+b3JKMWnFskCux2mPR9VSPo5tngQxdrEwruAyhXuNB/JuROa97mmsx7",
	"GOKNAFbOfqG+h7kG8D9b/P3mMeQWN25Iw0bc3KNaN0pUdb5fc/m2IwsKXMrxnY91QEXERKFlGRND12Vs",
	"VL2m6y949GRm/47mW7xL0+tbXPOZkQ7k17e+brz3b2pobH5qZUWSlyzLbWZrl9mu8lYch8NY2AFVGb1P",
	"2EmlU+jYyGzLJgdKyOFEEcOeYC1gVezELy9KqQwoZnhOFrng3UljlIahxx398w2TLJ2fWsfwAxA8seve",
	"gxxJuvMCFTnmNtX5PqnN967tvkSKv6pxsUaQv8YPRjJw61Vho7ChaW/lJF0iyN8v+9DPbt+HfuJ+FTK/",
	"F3Z4cDgrs+/d3cF5G2qRuTG9zcutOUndDG5y5CmmRm7HzPuPNidv5IpPZvlxW71fi2onJNY9l80BLpp/",
	"Ic97eyv/uzRfdwjderXXbP5HrvRuXmdhGaxd761X1Xm835FLGIzuvGePsF5ZDzW9qg1g6xRK7xTKT06h",
	"U+VO2WDeo2+mjfEezspkW4k+r7x/GLPED169f4dxg6CiPq+6mQkPcvdQEzm0ddUj0ZzovDO8nqfBA+pE",
	"R/27nsNJx3orD28p2Fj7r43guGHphH+M3rlovj94udRe+gonFeaTYHAAg0q4rjwz+7XRjr32a1ci3a2y",
	"WUL+rSv6yaEKqOoHvD5NXc+Jar+GubTY7xCxKHP4GZyd5aY/gY2LZNyOONDdWfdz0/pqSmSiUyXram3U",
	"ssq/j01l3jdfdIr+5Kci3k8qdlHFEg9S0ljqen3WS0vntRJ5t9rzmxtN5rh0JJax6VaTzbv9DF1Tc3iX",
	"WnPHQu3neN1IGPaWDXTZtJFnfqZo0/e+tt/7mYfxo1HFPh/5SSXP06zbqTsn2gzvj2wzfAesoVr7+TlU",
	"Tk4QPtQE2q+Wcm2koiK2tST9VbOCj4ioWzv4E1kHZP0VargfynbTaVcm4eZreNr9o192zihpLaI7Bv4A",
	"CMPHlRywJBh/6SZv5RSpzWQncUcKL6g5pNIOYgVdVrNfrfKc/dpbqvl3NP90S7hS7m1hOS50aqdVL/uo",
	"fzAk78+deguGja4NQzazjf/kQUhHYHOu0z2l0brag3j5zH6/8+dVObRSyRR1/UWnCclXP32K20GpdqKT",
	"T5n2sNM3/g13SGvBR0iXKgm7iHq022BlH/5Lmj2IuhsedojyqS777Y/lSHsJOsAL2/LfOHGe9HYDha84",
	"5UIboCu9gUni74QrZtTsF/qmfS9eDx0Md4jW7gdR+jvXWsAdcdgheb5k5OG9eE6VCEiQHKgaud0JLhQT",
	"tJuWbK/eeVozX7r14Y3hbM0f35I8JYOqX2GQDlZ2lCcjFZBHcVSp3A/Z3N+xRS35mdRm/8nwydAKZw9A",
	"T7bsxM3gyj2d2kYGD7hnznpKZpM/TuspLF4P+VUtJuN8+ba1p7iP8dTzSabNfxk2OWo72PN5+EF6N42T",
	"ZZUCtvuYFVxUpCCnna8ooFj6fXz2fG5sz0jYMZduOL3vGXPTm5LUzpM89pcnbOsbY8rvRT6N2RHtFcbs",
	"CAo84gb/emQUT03MVGWAJd0BOMl2PBJKGguWTTJXWrrhNs1QIItBlnJUykbHmspP7T4darU/1JPBnHXh",
	"kQ1VL6rbvOd0+XCOQWf6p8NCZ9ZnM5J6ynDJBygDQGpDrycTjBnqOPgEwrT52MDLcOao5Xax5jNObNoz",
	"m7SGdzASB4RlG6twJGY//e36he0NVfDpAy6Kyk1Y7X4E4aWtrddu/l3wXY+4+7GDuP9bB9u39yFNj95W",
	"dV++vfz/AwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
